---
schema: armada/ChartGroup/v1
metadata:
  schema: metadata/Document/v1
  name: ucp-shipyard
  layeringDefinition:
    abstract: false
    layer: global
  storagePolicy: cleartext
data:
  description: Shipyard
  chart_group:
    - ucp-rabbitmq-etcd
    - ucp-rabbitmq
    - ucp-shipyard
