---
schema: armada/Chart/v1
metadata:
  schema: metadata/Document/v1
  name: ucp-shipyard
  layeringDefinition:
    abstract: false
    layer: global
  storagePolicy: cleartext
  substitutions:
    # Chart source
    - src:
        schema: pegleg/SoftwareVersions/v1
        name: software-versions
        path: .charts.ucp.shipyard
      dest:
        path: .source

    # Images
    - src:
        schema: pegleg/SoftwareVersions/v1
        name: software-versions
        path: .images.ucp.shipyard
      dest:
        path: .values.images.tags

    # Node ports
    - src:
        schema: pegleg/CommonAddresses/v1
        name: common-addresses
        path: .node_ports.shipyard_api
      dest:
        path: .values.network.shipyard.node_port
    - src:
        schema: pegleg/CommonAddresses/v1
        name: common-addresses
        path: .node_ports.airflow_web
      dest:
        path: .values.network.airflow.web.node_port

    # Endpoints
    - src:
        schema: pegleg/EndpointCatalogue/v1
        name: ucp_endpoints
        path: .ucp.identity
      dest:
        path: .values.endpoints.identity
    - src:
        schema: pegleg/EndpointCatalogue/v1
        name: ucp_endpoints
        path: .ucp.postgresql
      dest:
        path: .values.endpoints.postgresql_shipyard_db
    - src:
        schema: pegleg/EndpointCatalogue/v1
        name: ucp_endpoints
        path: .ucp.postgresql
      dest:
        path: .values.endpoints.postgresql_airflow_db
    - src:
        schema: pegleg/EndpointCatalogue/v1
        name: ucp_endpoints
        path: .ucp.postgresql_airflow_celery
      dest:
        path: .values.endpoints.postgresql_airflow_celery_db
    - src:
        schema: pegleg/EndpointCatalogue/v1
        name: ucp_endpoints
        path: .ucp.shipyard
      dest:
        path: .values.endpoints.shipyard
    - src:
        schema: pegleg/EndpointCatalogue/v1
        name: ucp_endpoints
        path: .ucp.airflow_web
      dest:
        path: .values.endpoints.airflow_web
    - src:
        schema: pegleg/EndpointCatalogue/v1
        name: ucp_endpoints
        path: .ucp.airflow_flower
      dest:
        path: .values.endpoints.airflow_flower
    - src:
        schema: pegleg/EndpointCatalogue/v1
        name: ucp_endpoints
        path: .ucp.oslo_messaging
      dest:
        path: .values.endpoints.olso_messaging
    - src:
        schema: pegleg/EndpointCatalogue/v1
        name: ucp_endpoints
        path: .ucp.oslo_cache
      dest:
        path: .values.endpoints.oslo_cache

    # Database path
    - src:
        schema: pegleg/AccountCatalogue/v1
        name: ucp_service_accounts
        path: .ucp.shipyard.postgres.database
      dest:
        path: .values.endpoints.postgresql_shipyard_db.path
        pattern: 'DB_NAME'
    - src:
        schema: pegleg/AccountCatalogue/v1
        name: ucp_service_accounts
        path: .ucp.airflow.postgres.database
      dest:
        path: .values.endpoints.postgresql_airflow_db.path
        pattern: 'DB_NAME'
    - src:
        schema: pegleg/AccountCatalogue/v1
        name: ucp_service_accounts
        path: .ucp.airflow.postgres.database
      dest:
        path: .values.endpoints.postgresql_airflow_celery_db.path
        pattern: 'DB_NAME'
    # Credentials
    - src:
        schema: pegleg/AccountCatalogue/v1
        name: ucp_service_accounts
        path: .ucp.postgres.admin
      dest:
        path: .values.endpoints.postgresql_shipyard_db.auth.admin
    - src:
        schema: pegleg/AccountCatalogue/v1
        name: ucp_service_accounts
        path: .ucp.postgres.admin
      dest:
        path: .values.endpoints.postgresql_airflow_db.auth.admin
    - src:
        schema: pegleg/AccountCatalogue/v1
        name: ucp_service_accounts
        path: .ucp.postgres.admin
      dest:
        path: .values.endpoints.postgresql_airflow_celery_db.auth.admin
    - src:
        schema: pegleg/AccountCatalogue/v1
        name: ucp_service_accounts
        path: .ucp.keystone.admin
      dest:
        path: .values.endpoints.identity.auth.admin
    - src:
        schema: pegleg/AccountCatalogue/v1
        name: ucp_service_accounts
        path: .ucp.shipyard.postgres
      dest:
        path: .values.endpoints.postgresql_shipyard_db.auth.user
    - src:
        schema: pegleg/AccountCatalogue/v1
        name: ucp_service_accounts
        path: .ucp.airflow.postgres
      dest:
        path: .values.endpoints.postgresql_airflow_db.auth.user
    - src:
        schema: pegleg/AccountCatalogue/v1
        name: ucp_service_accounts
        path: .ucp.airflow.postgres
      dest:
        path: .values.endpoints.postgresql_airflow_celery_db.auth.user
    - src:
        schema: pegleg/AccountCatalogue/v1
        name: ucp_service_accounts
        path: .ucp.airflow.oslo_messaging
      dest:
        path: .values.endpoints.oslo_messaging.auth.user

    # Secrets
    - dest:
        path: .values.endpoints.identity.auth.admin.password
      src:
        schema: deckhand/Passphrase/v1
        name: ucp_keystone_admin_password
        path: .
    - dest:
        path: .values.endpoints.postgresql_shipyard_db.auth.admin.password
      src:
        schema: deckhand/Passphrase/v1
        name: ucp_postgres_admin_password
        path: .
    - dest:
        path: .values.endpoints.postgresql_airflow_db.auth.admin.password
      src:
        schema: deckhand/Passphrase/v1
        name: ucp_postgres_admin_password
        path: .
    - dest:
        path: .values.endpoints.postgresql_airflow_celery_db.auth.admin.password
      src:
        schema: deckhand/Passphrase/v1
        name: ucp_postgres_admin_password
        path: .
    - dest:
        path: .values.endpoints.identity.auth.user.password
      src:
        schema: deckhand/Passphrase/v1
        name: ucp_shipyard_keystone_password
        path: .
    - dest:
        path: .values.endpoints.postgresql_shipyard_db.auth.user.password
      src:
        schema: deckhand/Passphrase/v1
        name: ucp_shipyard_postgres_password
        path: .
    - dest:
        path: .values.endpoints.postgresql_airflow_db.auth.user.password
      src:
        schema: deckhand/Passphrase/v1
        name: ucp_airflow_postgres_password
        path: .
    - dest:
        path: .values.endpoints.postgresql_airflow_celery_db.auth.user.password
      src:
        schema: deckhand/Passphrase/v1
        name: ucp_airflow_postgres_password
        path: .
    - src:
        schema: deckhand/Passphrase/v1
        name: ucp_oslo_messaging_password
        path: .
      dest:
        path: .values.endpoints.oslo_messaging.auth.user.password

data:
  chart_name: shipyard
  release: ucp-shipyard
  namespace: ucp
  install:
    no_hooks: false
  upgrade:
    no_hooks: false
  values:
    endpoints:
      postgresql_airflow_db:
        name: postgresql
        hosts:
          default: postgresql
        path: /DB_NAME
        scheme: postgresql+psycopg2
        port:
          postgresql:
            default: 5432
        host_fqdn_override:
          default: null
      postgresql_shipyard_db:
        name: postgresql
        hosts:
          default: postgresql
        path: /DB_NAME
        scheme: postgresql+psycopg2
        port:
          postgresql:
            default: 5432
        host_fqdn_override:
          default: null
    prod_environment: true
    pod:
      replicas:
        shipyard:
          api: 2
        airflow:
          web: 2
          worker: 2
          flower: 2
          scheduler: 2
    labels:
      node_selector_key: ucp-control-plane
      node_selector_value: enabled
    network:
      shipyard:
        enable_node_port: true
      airflow:
        web:
          enable_node_port: true
    conf:
      shipyard:
        keystone_authtoken:
          memcache_security_strategy: None
...

