---
schema: armada/ChartGroup/v1
metadata:
  schema: metadata/Document/v1
  name: kubernetes-etcd
  layeringDefinition:
    abstract: false
    layer: global
  storagePolicy: cleartext
data:
  description: Kubernetes etcd
  chart_group:
    - kubernetes-etcd
