---
schema: armada/Chart/v1
metadata:
  schema: metadata/Document/v1
  name: jenkins
  layeringDefinition:
    abstract: false
    layer: site
  storagePolicy: cleartext
  substitutions:
    # Source
    - src:
        schema: pegleg/SoftwareVersions/v1
        name: software-versions
        path: .charts.jenkins
      dest:
        path: .source
    # Images
    - src:
        schema: pegleg/SoftwareVersions/v1
        name: software-versions
        path: .images.osh_infra_addons.jenkins
      dest:
        path: .values.images.tags
    # Endpoints
    - src:
        schema: pegleg/EndpointCatalogue/v1
        name: osh_endpoints
        path: .osh.identity
      dest:
        path: .values.endpoints.identity
    # Accounts
    - src:
        schema: pegleg/AccountCatalogue/v1
        name: osh_infra_addons_service_accounts
        path: .osh_infra_addons.jenkins
      dest:
        path: .values.endpoints.identity.auth
    - src:
        schema: pegleg/AccountCatalogue/v1
        name: osh_service_accounts
        path: .osh.keystone.admin
      dest:
        path: .values.endpoints.identity.auth.admin
    # Secrets
    - dest:
        path: .values.endpoints.identity.auth.admin.password
      src:
        schema: deckhand/Passphrase/v1
        name: osh_keystone_admin_password
        path: .
    - dest:
        path: .values.endpoints.identity.auth.jenkins.password
      src:
        schema: deckhand/Passphrase/v1
        name: osh_infra_addons_jenkins_password
        path: .
data:
  chart_name: jenkins
  release: jenkins
  namespace: openstack
  timeout: 1800
  install:
    no_hooks: false
  upgrade:
    no_hooks: false
  values:
    labels:
      node_selector_key: ucp-control-plane
      node_selector_value: enabled
  dependencies:
   - osh-helm-toolkit
...
