---
schema: armada/Chart/v1
metadata:
  schema: metadata/Document/v1
  name: libvirt
  layeringDefinition:
    abstract: false
    layer: global
  storagePolicy: cleartext
  substitutions:
    # Chart source
    - src:
        schema: pegleg/SoftwareVersions/v1
        name: software-versions
        path: .charts.osh.libvirt
      dest:
        path: .source
data:
  chart_name: libvirt
  release: libvirt
  namespace: openstack
  timeout: 300
  install:
    no_hooks: false
  upgrade:
    no_hooks: false
  values:
    labels:
      agent:
        libvirt:
          node_selector_key: openstack-compute-node
          node_selector_value: enabled
  dependencies:
    - osh-helm-toolkit
