---
schema: armada/Chart/v1
metadata:
  schema: metadata/Document/v1
  name: openvswitch
  layeringDefinition:
    abstract: false
    layer: global
  storagePolicy: cleartext
  substitutions:
    # Chart source
    - src:
        schema: pegleg/SoftwareVersions/v1
        name: software-versions
        path: .charts.osh.openvswitch
      dest:
        path: .source

    # External Interface
    - src:
        schema: pegleg/CommonAddresses/v1
        name: common-addresses
        path: .openvswitch.external_iface
      dest:
        path: .values.network.interface.external
        pattern: 'EXTERNAL_INTERFACE'
data:
  chart_name: openvswitch
  release: openvswitch
  namespace: openstack
  timeout: 300
  install:
    no_hooks: false
  upgrade:
    no_hooks: false
  values:
    labels:
      ovs:
        node_selector_key: openvswitch
        node_selector_value: enabled
    network:
      interface:
        external: 'EXTERNAL_INTERFACE'
  dependencies:
    - osh-helm-toolkit
