---
schema: armada/Chart/v1
metadata:
  schema: metadata/Document/v1
  name: ucp-ceph
  layeringDefinition:
    abstract: false
    layer: global
  storagePolicy: cleartext
  substitutions:
    # Chart source
    - src:
        schema: pegleg/SoftwareVersions/v1
        name: software-versions
        path: .charts.ucp.ceph
      dest:
        path: .source

    # Images
    - src:
        schema: pegleg/SoftwareVersions/v1
        name: software-versions
        path: .images.ceph.ceph
      dest:
        path: .values.images.tags

    # IP addresses
    - src:
        schema: pegleg/CommonAddresses/v1
        name: common-addresses
        path: .storage.ceph.public_cidr
      dest:
        path: .values.network.public
    - src:
        schema: pegleg/CommonAddresses/v1
        name: common-addresses
        path: .storage.ceph.cluster_cidr
      dest:
        path: .values.network.cluster
    - src:
        schema: pegleg/EndpointCatalogue/v1
        name: ucp_endpoints
        path: .ucp.identity
      dest:
        path: .values.endpoints.identity
    - src:
        schema: pegleg/EndpointCatalogue/v1
        name: ucp_endpoints
        path: .ceph.object_store
      dest:
        path: .values.endpoints.object_store
    - src:
        schema: pegleg/EndpointCatalogue/v1
        name: ucp_endpoints
        path: .ceph.ceph_mon
      dest:
        path: .values.endpoints.ceph_mon
    - src:
        schema: pegleg/EndpointCatalogue/v1
        name: ucp_endpoints
        path: .ceph.ceph_mgr
      dest:
        path: .values.endpoints.ceph_mgr
    - src:
        schema: pegleg/AccountCatalogue/v1
        name: ucp_service_accounts
        path: .ucp.keystone.admin
      dest:
        path: .values.endpoints.identity.auth.admin
    - src:
        schema: pegleg/AccountCatalogue/v1
        name: ucp_service_accounts
        path: .ceph.swift.keystone
      dest:
        path: .values.endpoints.identity.auth.swift

    # Secrets
    - dest:
        path: .values.endpoints.identity.auth.admin.password
      src:
        schema: deckhand/Passphrase/v1
        name: ucp_keystone_admin_password
        path: .
    - dest:
        path: .values.endpoints.identity.auth.swift.password
      src:
        schema: deckhand/Passphrase/v1
        name: ceph_swift_keystone_password
        path: .
data:
  chart_name: ceph
  release: ucp-ceph
  namespace: ceph
  # NOTE(alanmeadows): Armada seems to wait forever for ceph
  # requiring the operator to wait for the timeout or kill
  # armada to re-run it
  #
  # as far as I can tell, its "up" and ready after a few
  # minutes
  timeout: 300
  wait:
    timeout: 300
    labels:
      release_group: ucp-ceph
  install:
    no_hooks: false
  upgrade:
    no_hooks: false
    pre:
      delete:
        - name: ceph-bootstrap
          type: job
          labels:
            - application: ceph
            - component: bootstrap
            - release_group: armada-ucp
        - name: ceph-mds-keyring-generator
          type: job
          labels:
            - application: ceph
            - component: mds-keyring-generator
            - release_group: armada-ucp
        - name: ceph-mon-keyring-generator
          type: job
          labels:
            - application: ceph
            - component: mon-keyring-generator
            - release_group: armada-ucp
        - name: ceph-rgw-keyring-generator
          type: job
          labels:
            - application: ceph
            - component: rgw-keyring-generator
            - release_group: armada-ucp
        - name: ceph-storage-keys-generator
          type: job
          labels:
            - application: ceph
            - component: storage-keys-generator
            - release_group: armada-ucp
        - name: ceph-osd-keyring-generator
          type: job
          labels:
            - application: ceph
            - component: osd-keyring-generator
            - release_group: armada-ucp
  # TODO(alanmeadows) we do not pass network
  values:
    labels:
      job:
        node_selector_key: ucp-control-plane
        node_selector_value: enabled
      provisioner:
        node_selector_key: ucp-control-plane
        node_selector_value: enabled
    ceph:
      rgw_keystone_auth: true
    deployment:
      ceph: true
      client_secrets: false
      rbd_provisioner: true
      rgw_keystone_user_and_endpoints: false
      storage_secrets: true
    bootstrap:
      enabled: true
    conf:
      storage:
        osd:
          - data:
              type: directory
              location: /var/lib/openstack-helm/ceph/osd/osd-one
            journal:
              type: directory
              location: /var/lib/openstack-helm/ceph/osd/journal-one
      osd:
        # NOTE(alanmeadows): This is required ATM for bootstrapping a Ceph
        # cluster with only one OSD.  Depending on OSD targeting & site
        # configuration this can be changed.
        osd_crush_chooseleaf_type: 0
      pool:

        # NOTE(alanmeadowS) spport 4.x 16.04 kernels (non-HWE)
        crush:
          tunables: 'hammer'

        # NOTE(alanmeadows): This is required ATM for bootstrapping a Ceph
        # cluster with only one OSD.  Depending on OSD targeting & site
        # configuration this can be changed.
        target:
          osd: 1
          pg_per_osd: 100

        default:
            # NOTE(alanmeadows): This is required ATM for bootstrapping a Ceph
            # cluster with only one OSD.  Depending on OSD targeting & site
            # configuration this can be changed.
          crush_rule: same_host

      ceph:
          global:
            # NOTE(mb874d): This is required ATM for bootstrapping a Ceph
            # cluster with only one OSD.  Depending on OSD targeting & site
            # configuration this can be changed.
            osd_pool_default_size: 1

            # specify fsid
            fsid: '88904ebb-f6fc-48b1-80ec-e1915cfa84a9'

  dependencies:
    - ceph_htk
...
---
schema: armada/Chart/v1
metadata:
  schema: metadata/Document/v1
  name: ceph_htk
  layeringDefinition:
    abstract: false
    layer: global
  storagePolicy: cleartext
data:
  chart_name: ceph_htk
  release: ceph_htk
  namespace: ceph_htk
  timeout: 100
  values: {}
  source:
    type: git
    location: https://github.com/openstack/openstack-helm
    subpath: helm-toolkit
    reference: d5f880c1ee5111c0e6889323fa4b7138c36f2673
  dependencies: []
...

