---
schema: armada/Chart/v1
metadata:
  schema: metadata/Document/v1
  name: ucp-ceph
  layeringDefinition:
    abstract: false
    layer: global
  storagePolicy: cleartext
  substitutions:
    # Chart source
    - src:
        schema: SoftwareVersions/v1
        name: software-versions
        path: .charts.ucp.ceph
      dest:
        path: .source

    # Images
    - src:
        schema: SoftwareVersions/v1
        name: software-versions
        path: .images.ceph.ceph
      dest:
        path: .values.images.tags

    # IP addresses
    - src:
        schema: pegleg/CommonAddresses/v1
        name: common-addresses
        path: .storage.ceph.public_cidr
      dest:
        path: .network.public
    - src:
        schema: pegleg/CommonAddresses/v1
        name: common-addresses
        path: .storage.ceph.cluster_cidr
      dest:
        path: .network.cluster
    - src:
        schema: EndpointCatalogue/v1
        name: ucp_endpoints
        path: .ucp.identity
      dest:
        path: .values.endpoints.identity
    - src:
        schema: EndpointCatalogue/v1
        name: ucp_endpoints
        path: .ceph.object_store
      dest:
        path: .values.endpoints.object_store
    - src:
        schema: EndpointCatalogue/v1
        name: ucp_endpoints
        path: .ceph.ceph_mon
      dest:
        path: .values.endpoints.ceph_mon
    - src:
        schema: EndpointCatalogue/v1
        name: ucp_endpoints
        path: .ceph.ceph_mgr
      dest:
        path: .values.endpoints.ceph_mgr
    - src:
        schema: AccountCatalogue/v1
        name: ucp_service_accounts
        path: .ucp.keystone.admin
      dest:
        path: .values.endpoints.identity.auth.admin
    - src:
        schema: AccountCatalogue/v1
        name: ucp_service_accounts
        path: .ceph.swift.keystone
      dest:
        path: .values.endpoints.identity.auth.swift

    # Secrets
    - dest:
        path: .values.endpoints.identity.auth.admin.password
      src:
        schema: deckhand/Passphrase/v1
        name: ucp_keystone_admin_password
        path: .
    - dest:
        path: .values.endpoints.identity.auth.swift.password
      src:
        schema: deckhand/Passphrase/v1
        name: ceph_swift_keystone_password
        path: .
data:
  chart_name: ceph
  release: ucp-ceph
  namespace: ceph
  timeout: 3600
  wait:
    timeout: 3600
    labels:
      release_group: ucp-ceph
  install:
    no_hooks: false
  upgrade:
    no_hooks: false
    pre:
      delete:
        - name: ceph-bootstrap
          type: job
          labels:
            - application: ceph
            - component: bootstrap
            - release_group: armada-ucp
        - name: ceph-mds-keyring-generator
          type: job
          labels:
            - application: ceph
            - component: mds-keyring-generator
            - release_group: armada-ucp
        - name: ceph-mon-keyring-generator
          type: job
          labels:
            - application: ceph
            - component: mon-keyring-generator
            - release_group: armada-ucp
        - name: ceph-rgw-keyring-generator
          type: job
          labels:
            - application: ceph
            - component: rgw-keyring-generator
            - release_group: armada-ucp
        - name: ceph-storage-keys-generator
          type: job
          labels:
            - application: ceph
            - component: storage-keys-generator
            - release_group: armada-ucp
        - name: ceph-osd-keyring-generator
          type: job
          labels:
            - application: ceph
            - component: osd-keyring-generator
            - release_group: armada-ucp
  values:
    labels:
      jobs:
        node_selector_key: ucp-control-plane
        node_selector_value: enabled
    ceph:
      rgw_keystone_auth: true
      storage:
        osd_directory: /var/lib/openstack-helm/ceph/osd
    deployment:
      ceph: true
      client_secrets: false
      rbd_provisioner: true
      rgw_keystone_user_and_endpoints: false
      storage_secrets: true
    bootstrap:
      enabled: true
    conf:
      ceph:
        config:
          global:
            # NOTE(mb874d): This is required ATM for bootstrapping a Ceph
            # cluster with only one OSD.  Depending on OSD targeting & site
            # configuration this can be changed.
            osd_pool_default_size: 1
  dependencies:
    - ceph_htk
...
---
schema: armada/Chart/v1
metadata:
  schema: metadata/Document/v1
  name: ceph_htk
  layeringDefinition:
    abstract: false
    layer: global
  storagePolicy: cleartext
data:
  chart_name: ceph_htk
  release: ceph_htk
  namespace: ceph_htk
  timeout: 100
  values: {}
  source:
    type: git
    location: https://github.com/openstack/openstack-helm
    subpath: helm_toolkit
    reference: e4dd1ba91a9e3c517b0f4594c70eb9a743681432
  dependencies: []
...
