---
schema: armada/ChartGroup/v1
metadata:
  schema: metadata/Document/v1
  name: kubernetes-dns
  layeringDefinition:
    abstract: false
    layer: global
  storagePolicy: cleartext
data:
  description: Cluster DNS
  chart_group:
    - coredns
