---
schema: armada/Chart/v1
metadata:
  schema: metadata/Document/v1
  name: kubernetes-calico-etcd
  layeringDefinition:
    abstract: false
    layer: site
    parentSelector:
        name: kubernetes-calico-etcd-global
    actions:
        - method: merge
          path: .
  storagePolicy: cleartext
  substitutions:

    # Chart source
    - src:
        schema: pegleg/SoftwareVersions/v1
        name: software-versions
        path: .charts.calico.etcd
      dest:
        path: .source

    # Image versions
    - src:
        schema: pegleg/SoftwareVersions/v1
        name: software-versions
        path: .images.calico.etcd
      dest:
        path: .values.images.tags

    # IP addresses
    -
      src:
        schema: pegleg/CommonAddresses/v1
        name: common-addresses
        path: .calico.etcd.service_ip
      dest:
        path: .values.service.ip
    -
      src:
        schema: pegleg/CommonAddresses/v1
        name: common-addresses
        path: .calico.etcd.service_ip
      dest:
        path: .values.anchor.etcdctl_endpoint

    # CAs
    -
      src:
        schema: deckhand/CertificateAuthority/v1
        name: calico-etcd
        path: .
      dest:
        path: .values.secrets.tls.client.ca
    -
      src:
        schema: deckhand/CertificateAuthority/v1
        name: calico-etcd-peer
        path: .
      dest:
        path: .values.secrets.tls.peer.ca

    # Anchor client cert
    -
      src:
        schema: deckhand/Certificate/v1
        name: calico-etcd-anchor
        path: .
      dest:
        path: .values.secrets.anchor.tls.cert
    -
      src:
        schema: deckhand/CertificateKey/v1
        name: calico-etcd-anchor
        path: .
      dest:
        path: .values.secrets.anchor.tls.key

    # Node names
    -
      src:
        schema: pegleg/CommonAddresses/v1
        name: common-addresses
        path: .masters[0].hostname
      dest:
        path: .values.nodes[0].name
    -
      src:
        schema: pegleg/CommonAddresses/v1
        name: common-addresses
        path: .masters[1].hostname
      dest:
        path: .values.nodes[1].name

      src:
        schema: pegleg/CommonAddresses/v1
        name: common-addresses
        path: .genesis.hostname
      dest:
        path: .values.nodes[2].name

   # Server certs
    -
      src:
        schema: deckhand/Certificate/v1
        name: calico-etcd-clcpdemo2
        path: .
      dest:
        path: .values.nodes[0].tls.client.cert
    -
      src:
        schema: deckhand/CertificateKey/v1
        name: calico-etcd-clcpdemo2
        path: .
      dest:
        path: .values.nodes[0].tls.client.key
    -
      src:
        schema: deckhand/Certificate/v1
        name: calico-etcd-clcpdemo2-peer
        path: .
      dest:
        path: .values.nodes[0].tls.peer.cert
    -
      src:
        schema: deckhand/CertificateKey/v1
        name: calico-etcd-clcpdemo2-peer
        path: .
      dest:
        path: .values.nodes[0].tls.peer.key

    -
      src:
        schema: deckhand/Certificate/v1
        name: calico-etcd-clcpdemo3
        path: .
      dest:
        path: .values.nodes[1].tls.client.cert
    -
      src:
        schema: deckhand/CertificateKey/v1
        name: calico-etcd-clcpdemo3
        path: .
      dest:
        path: .values.nodes[1].tls.client.key
    -
      src:
        schema: deckhand/Certificate/v1
        name: calico-etcd-clcpdemo3-peer
        path: .
      dest:
        path: .values.nodes[1].tls.peer.cert
    -
      src:
        schema: deckhand/CertificateKey/v1
        name: calico-etcd-clcpdemo3-peer
        path: .
      dest:
        path: .values.nodes[1].tls.peer.key

    # NOTE(mb874d): Be sure we generate these certs for genesis.
    -
      src:
        schema: deckhand/Certificate/v1
        name: calico-etcd-clcp-demo-1
        path: .
      dest:
        path: .values.nodes[2].tls.client.cert
    -
      src:
        schema: deckhand/CertificateKey/v1
        name: calico-etcd-clcp-demo-1
        path: .
      dest:
        path: .values.nodes[2].tls.client.key
    -
      src:
        schema: deckhand/Certificate/v1
        name: calico-etcd-clcp-demo-1-peer
        path: .
      dest:
        path: .values.nodes[2].tls.peer.cert
    -
      src:
        schema: deckhand/CertificateKey/v1
        name: calico-etcd-clcp-demo-1-peer
        path: .
      dest:
        path: .values.nodes[2].tls.peer.key
        

data: {}

...
