---
schema: armada/ChartGroup/v1
metadata:
  schema: metadata/Document/v1
  name: openstack-ceph-config
  layeringDefinition:
    abstract: false
    layer: global
  storagePolicy: cleartext
data:
  description: Ceph config for OpenStack namespace(s)
  chart_group:
    - openstack-ceph-config
