---
schema: armada/Chart/v1
metadata:
  schema: metadata/Document/v1
  name: ucp-divingbell
  layeringDefinition:
    abstract: false
    layer: global
  storagePolicy: cleartext
  substitutions:
    # Chart source
    - src:
        schema: pegleg/SoftwareVersions/v1
        name: software-versions
        path: .charts.ucp.divingbell
      dest:
        path: .source
data:
  chart_name: divingbell
  release: divingbell
  namespace: ucp
  timeout: 300
  install:
    no_hooks: false
  upgrade:
    no_hooks: false
  values:
    conf:
      overrides:
        divingbell_mounts:
          labels:
          - label:
              key: hosttype
              values:
              - "nd-global"
              - "nv-global"
            conf:
              mounts:
                mnt1:
                  mnt_tgt: /hugepages
                  device: hugetlbfs
                  type: hugetlbfs
  dependencies: []