---
schema: armada/ChartGroup/v1
metadata:
  schema: metadata/Document/v1
  name: ingress-kube-system
  layeringDefinition:
    abstract: false
    layer: global
  storagePolicy: cleartext
data:
  description: Ingress for the site
  chart_group:
    - ingress-kube-system
