---
schema: armada/Chart/v1
metadata:
  schema: metadata/Document/v1
  name: osh-nova-memcached
  layeringDefinition:
    abstract: false
    layer: global
  storagePolicy: cleartext
  substitutions:
    # Chart source
    - src:
        schema: pegleg/SoftwareVersions/v1
        name: software-versions
        path: .charts.osh.memcached
      dest:
        path: .source

    # Images
    - src:
        schema: pegleg/SoftwareVersions/v1
        name: software-versions
        path: .images.osh.memcached
      dest:
        path: .values.images.tags

    - src:
        schema: pegleg/EndpointCatalogue/v1
        name: osh_endpoints
        path: .osh.nova_oslo_cache
      dest:
        path: .values.endpoints.oslo_cache
data:
  chart_name: osh-nova-memcached
  release: osh-nova-memcached
  namespace: openstack
  install:
    no_hooks: false
  upgrade:
    no_hooks: false
  values:
    labels:
      server:
        node_selector_key: openstack-control-plane
        node_selector_value: enabled
  dependencies:
    - osh-helm-toolkit
...
