---
schema: armada/Manifest/v1
metadata:
  schema: metadata/Document/v1
  name: openstack-helm
  layeringDefinition:
    abstract: false
    layer: global
  storagePolicy: cleartext
data:
  release_prefix: osh
  chart_groups:
    - openstack-ingress-controller
    - openstack-ceph-config
    - openstack-mariadb
    - openstack-compute-services
    - openstack-keystone
    - openstack-glance
    - openstack-cinder
    - openstack-compute-kit
    - openstack-heat
    - openstack-horizon
