---
schema: armada/Chart/v1
metadata:
  schema: metadata/Document/v1
  name: ucp-ceph
  layeringDefinition:
    abstract: false
    layer: global
  storagePolicy: cleartext
  substitutions:
    # Chart source
    - src:
        schema: pegleg/SoftwareVersions/v1
        name: software-versions
        path: .charts.ucp.ceph
      dest:
        path: .source

    # Images
    - src:
        schema: pegleg/SoftwareVersions/v1
        name: software-versions
        path: .images.ceph.ceph
      dest:
        path: .values.images.tags

    # IP addresses
    - src:
        schema: pegleg/CommonAddresses/v1
        name: common-addresses
        path: .storage.ceph.public_cidr
      dest:
        path: .values.network.public
    - src:
        schema: pegleg/CommonAddresses/v1
        name: common-addresses
        path: .storage.ceph.cluster_cidr
      dest:
        path: .values.network.cluster
    - src:
        schema: pegleg/EndpointCatalogue/v1
        name: ucp_endpoints
        path: .ucp.identity
      dest:
        path: .values.endpoints.identity
    - src:
        schema: pegleg/EndpointCatalogue/v1
        name: ucp_endpoints
        path: .ceph.object_store
      dest:
        path: .values.endpoints.object_store
    - src:
        schema: pegleg/EndpointCatalogue/v1
        name: ucp_endpoints
        path: .ceph.ceph_mon
      dest:
        path: .values.endpoints.ceph_mon
    - src:
        schema: pegleg/EndpointCatalogue/v1
        name: ucp_endpoints
        path: .ceph.ceph_mgr
      dest:
        path: .values.endpoints.ceph_mgr
    - src:
        schema: pegleg/AccountCatalogue/v1
        name: ucp_service_accounts
        path: .ucp.keystone.admin
      dest:
        path: .values.endpoints.identity.auth.admin
    - src:
        schema: pegleg/AccountCatalogue/v1
        name: ucp_service_accounts
        path: .ceph.swift.keystone
      dest:
        path: .values.endpoints.identity.auth.swift

    # Secrets
    - dest:
        path: .values.endpoints.identity.auth.admin.password
      src:
        schema: deckhand/Passphrase/v1
        name: ucp_keystone_admin_password
        path: .
    - dest:
        path: .values.endpoints.identity.auth.swift.password
      src:
        schema: deckhand/Passphrase/v1
        name: ceph_swift_keystone_password
        path: .
data:
  chart_name: ceph
  release: ucp-ceph
  namespace: ceph
  # NOTE(alanmeadows): Armada seems to wait forever for ceph
  # requiring the operator to wait for the timeout or kill
  # armada to re-run it
  #
  # as far as I can tell, its "up" and ready after a few
  # minutes
  timeout: 300
  wait:
    timeout: 300
    labels:
      release_group: ucp-ceph
  install:
    no_hooks: false
  upgrade:
    no_hooks: false
    pre:
      delete:
        - type: job
          labels:
            - application: ceph
            - component: bootstrap
            - release_group: armada-ucp
        - type: job
          labels:
            - application: ceph
            - component: mds-keyring-generator
            - release_group: armada-ucp
        - type: job
          labels:
            - application: ceph
            - component: mon-keyring-generator
            - release_group: armada-ucp
        - type: job
          labels:
            - application: ceph
            - component: rgw-keyring-generator
            - release_group: armada-ucp
        - type: job
          labels:
            - application: ceph
            - component: storage-keys-generator
            - release_group: armada-ucp
        - type: job
          labels:
            - application: ceph
            - component: osd-keyring-generator
            - release_group: armada-ucp
  values:
    labels:
      job:
        node_selector_key: ucp-control-plane
        node_selector_value: enabled
      provisioner:
        node_selector_key: ucp-control-plane
        node_selector_value: enabled
    endpoints:
      identity:
        namespace: openstack
      object_store:
        namespace: ceph
      ceph_mon:
        namespace: ceph
    ceph:
      rgw_keystone_auth: true
    deployment:
      ceph: true
      client_secrets: false
      rbd_provisioner: true
      cephfs_provisioner: true
      rgw_keystone_user_and_endpoints: false
      storage_secrets: true
    bootstrap:
      enabled: true
    conf:
      ceph:
        global:
          fsid: '88904ebb-f6fc-48b1-80ec-e1915cfa84a9'
      pool:
        crush:
          tunables: 'hammer'
        target:
          osd: 2
          pg_per_osd: 100
        default:
          crush_rule: same_host
        spec:
          # RBD pool
          - name: rbd
            application: rbd
            replication: 2
            percent_total_data: 40
          # CephFS pools
          - name: cephfs_metadata
            application: cephfs
            replication: 2
            percent_total_data: 5
          - name: cephfs_data
            application: cephfs
            replication: 2
            percent_total_data: 10
          # RadosGW pools
          - name: .rgw.root
            application: rgw
            replication: 2
            percent_total_data: 0.1
          - name: default.rgw.control
            application: rgw
            replication: 2
            percent_total_data: 0.1
          - name: default.rgw.data.root
            application: rgw
            replication: 2
            percent_total_data: 0.1
          - name: default.rgw.gc
            application: rgw
            replication: 2
            percent_total_data: 0.1
          - name: default.rgw.log
            application: rgw
            replication: 2
            percent_total_data: 0.1
          - name: default.rgw.intent-log
            application: rgw
            replication: 2
            percent_total_data: 0.1
          - name: default.rgw.meta
            application: rgw
            replication: 2
            percent_total_data: 0.1
          - name: default.rgw.usage
            application: rgw
            replication: 2
            percent_total_data: 0.1
          - name: default.rgw.users.keys
            application: rgw
            replication: 2
            percent_total_data: 0.1
          - name: default.rgw.users.email
            application: rgw
            replication: 2
            percent_total_data: 0.1
          - name: default.rgw.users.swift
            application: rgw
            replication: 2
            percent_total_data: 0.1
          - name: default.rgw.users.uid
            application: rgw
            replication: 2
            percent_total_data: 0.1
          - name: default.rgw.buckets.extra
            application: rgw
            replication: 2
            percent_total_data: 0.1
          - name: default.rgw.buckets.index
            application: rgw
            replication: 2
            percent_total_data: 3
          - name: default.rgw.buckets.data
            application: rgw
            replication: 2
            percent_total_data: 34.8
      storage:
        osd:
          - data:
              type: block-logical
              location: /dev/vdb
            journal:
              type: directory
              location: /var/lib/ceph/journal0/osd/journal-vdb
          - data:
              type: block-logical
              location: /dev/vdc
            journal:
              type: directory
              location: /var/lib/ceph/journal0/osd/journal-vdc
      overrides:
        ceph_osd:
          hosts:
            - name: controller02
              conf:
                storage:
                  osd:
                    - data:
                        type: block-logical
                        location: /dev/sdb
                      journal:
                        type: directory
                        location: /var/lib/openstack-helm/ceph/osd/journal-sdb
                    - data:
                        type: block-logical
                        location: /dev/sdc
                      journal:
                        type: directory
                        location: /var/lib/openstack-helm/ceph/osd/journal-sdc
                    - data:
                        type: block-logical
                        location: /dev/sdd
                      journal:
                        type: directory
                        location: /var/lib/openstack-helm/ceph/osd/journal-sdd
                    - data:
                        type: block-logical
                        location: /dev/sde
                      journal:
                        type: directory
                        location: /var/lib/openstack-helm/ceph/osd/journal-sde
                    - data:
                        type: block-logical
                        location: /dev/sdf
                      journal:
                        type: directory
                        location: /var/lib/openstack-helm/ceph/osd/journal-sdf
                    - data:
                        type: block-logical
                        location: /dev/sdg
                      journal:
                        type: directory
                        location: /var/lib/openstack-helm/ceph/osd/journal-sdg
                    - data:
                        type: block-logical
                        location: /dev/sdh
                      journal:
                        type: directory
                        location: /var/lib/openstack-helm/ceph/osd/journal-sdh
                    - data:
                        type: block-logical
                        location: /dev/sdi
                      journal:
                        type: directory
                        location: /var/lib/openstack-helm/ceph/osd/journal-sdi
                    - data:
                        type: block-logical
                        location: /dev/sdj
                      journal:
                        type: directory
                        location: /var/lib/openstack-helm/ceph/osd/journal-sdj
                    - data:
                        type: block-logical
                        location: /dev/sdk
                      journal:
                        type: directory
                        location: /var/lib/openstack-helm/ceph/osd/journal-sdk
  dependencies:
    - ceph_htk
...
---
schema: armada/Chart/v1
metadata:
  schema: metadata/Document/v1
  name: ceph_htk
  layeringDefinition:
    abstract: false
    layer: global
  storagePolicy: cleartext
data:
  chart_name: ceph_htk
  release: ceph_htk
  namespace: ceph_htk
  timeout: 100
  values: {}
  source:
    type: git
    location: https://github.com/openstack/openstack-helm
    subpath: helm-toolkit
    reference: d5f880c1ee5111c0e6889323fa4b7138c36f2673
  dependencies: []
...
