---
schema: armada/Chart/v1
metadata:
  schema: metadata/Document/v1
  name: ucp-mariadb
  layeringDefinition:
    abstract: false
    layer: global
  storagePolicy: cleartext
  substitutions:
    # Chart source
    - src:
        schema: SoftwareVersions/v1
        name: software-versions
        path: .charts.ucp.mariadb
      dest:
        path: .source

    # Images
    - src:
        schema: SoftwareVersions/v1
        name: software-versions
        path: .images.ucp.mariadb
      dest:
        path: .values.images.tags

    # Endpoints
    - src:
        schema: EndpointCatalogue/v1
        name: ucp_endpoints
        path: .ucp.oslo_db
      dest:
        path: .values.endpoints.olso_db
    # Accounts
    - src:
        schema: AccountCatalogue/v1
        name: ucp_service_accounts
        path: .ucp.oslo_db.admin
      dest:
        path: .values.endpoints.oslo_db.auth.admin

    # Secrets
    - dest:
        path: .values.endpoints.oslo_db.auth.admin.password
      src:
        schema: deckhand/Passphrase/v1
        name: ucp_oslo_db_admin_password
        path: .

data:
  chart_name: ucp-mariadb
  release: ucp-mariadb
  namespace: ucp
  install:
    no_hooks: false
  upgrade:
    no_hooks: false
  values: {}
  dependencies:
    - mariadb_htk
...
---
schema: armada/Chart/v1
metadata:
  schema: metadata/Document/v1
  name: mariadb_htk
  layeringDefinition:
    abstract: false
    layer: global
  storagePolicy: cleartext
data:
  chart_name: mariadb_htk
  release: mariadb_htk
  namespace: mariadb_htk
  timeout: 100
  values: {}
  source:
    type: git
    location: https://github.com/openstack/openstack-helm
    subpath: helm_toolkit
    reference: e4dd1ba91a9e3c517b0f4594c70eb9a743681432
  dependencies: []
...
