---
schema: armada/Chart/v1
metadata:
  schema: metadata/Document/v1
  name: ucp-postgresql
  layeringDefinition:
    abstract: false
    layer: global
  storagePolicy: cleartext
  substitutions:
    # Chart source
    - src:
        schema: SoftwareVersions/v1
        name: software-versions
        path: .charts.ucp.postgresql
      dest:
        path: .source

    # Images
    - src:
        schema: SoftwareVersions/v1
        name: software-versions
        path: .images.ucp.postgresql
      dest:
        path: .values.images.tags

    # Endpoints
    - src:
        schema: EndpointCatalogue/v1
        name: ucp_endpoints
        path: .ucp.postgresql
      dest:
        path: .values.endpoints.postgresql
    # Credentials
    - src:
        schema: AccountCatalogue/v1
        name: ucp_service_accounts
        path: .ucp.postgres.admin
      dest:
        path: .values.endpoints.postgresql.auth.admin

    # Secrets
    - dest:
        path: .values.endpoints.postgresql.auth.admin.password
      src:
        schema: deckhand/Passphrase/v1
        name: ucp_postgres_admin_password
        path: .
data:
  chart_name: ucp-postgresql
  release: ucp-postgresql
  namespace: ucp
  install:
    no_hooks: false
  upgrade:
    no_hooks: false
  pre:
    delete: []
    create: []
  post:
    delete: []
    create: []
  values:
    development:
      enabled: false
    labels:
      node_selector_key: ucp-control-plane
      node_selector_value: enabled
  dependencies:
    - postgres_htk
...
---
schema: armada/Chart/v1
metadata:
  schema: metadata/Document/v1
  name: postgres_htk
  layeringDefinition:
    abstract: false
    layer: global
  storagePolicy: cleartext
data:
  chart_name: postgres_htk
  release: postgres_htk
  namespace: postgres_htk
  timeout: 100
  values: {}
  source:
    type: git
    location: https://github.com/openstack/openstack-helm
    subpath: helm_toolkit
    reference: e4dd1ba91a9e3c517b0f4594c70eb9a743681432
  dependencies: []
...
