---
schema: armada/Chart/v1
metadata:
  schema: metadata/Document/v1
  name: ucp-keystone
  labels:
    component: keystone
    configuration: ldap-backed
  layeringDefinition:
    abstract: false
    layer: global
  storagePolicy: cleartext
  substitutions:
    # Chart source
    - src:
        schema: pegleg/SoftwareVersions/v1
        name: software-versions
        path: .charts.ucp.keystone
      dest:
        path: .source

    # Images
    - src:
        schema: pegleg/SoftwareVersions/v1
        name: software-versions
        path: .images.ucp.keystone
      dest:
        path: .values.images.tags

    # Endpoints
    - src:
        schema: EndpointCatalogue/v1
        name: ucp_endpoints
        path: .ucp.identity
      dest:
        path: .values.endpoints.identity
    - src:
        schema: EndpointCatalogue/v1
        name: ucp_endpoints
        path: .ucp.oslo_db
      dest:
        path: .values.endpoints.oslo_db
    - src:
        schema: EndpointCatalogue/v1
        name: ucp_endpoints
        path: .ucp.oslo_messaging
      dest:
        path: .values.endpoints.oslo_messaging
    - src:
        schema: EndpointCatalogue/v1
        name: ucp_endpoints
        path: .ucp.oslo_cache
      dest:
        path: .values.endpoints.oslo_cache
    - src:
        schema: AccountCatalogue/v1
        name: ucp_service_accounts
        path: .ucp.keystone.admin
      dest:
        path: .values.endpoints.identity.auth.admin
    - src:
        schema: AccountCatalogue/v1
        name: ucp_service_accounts
        path: .ucp.keystone.oslo_messaging
      dest:
        path: .values.endpoints.oslo_messaging.auth.keystone
    - src:
        schema: AccountCatalogue/v1
        name: ucp_service_accounts
        path: .ucp.keystone.oslo_db
      dest:
        path: .values.endpoints.oslo_db.auth.keystone
    - src:
        schema: AccountCatalogue/v1
        name: ucp_service_accounts
        path: .ucp.keystone.oslo_db.database
      dest:
        path: .values.endpoints.oslo_db.path
        pattern: DB_NAME

    # Secrets
    - dest:
        path: .values.endpoints.identity.auth.admin.password
      src:
        schema: deckhand/Passphrase/v1
        name: ucp_keystone_admin_password
        path: .
    - dest:
        path: .values.endpoints.oslo_messaging.auth.keystone.password
      src:
        schema: deckhand/Passphrase/v1
        name: ucp_oslo_messaging_password
        path: .
    - dest:
        path: .values.endpoints.oslo_db.auth.keystone.password
      src:
        schema: deckhand/Passphrase/v1
        name: ucp_keystone_oslo_db_password
        path: .
    - dest:
        path: .values.endpoints.oslo_db.auth.admin.password
      src:
        schema: deckhand/Passphrase/v1
        name: ucp_oslo_db_admin_password
        path: .
data:
  chart_name: ucp-keystone
  release: ucp-keystone
  namespace: ucp
  install:
    no_hooks: false
  upgrade:
    no_hooks: false
  pre:
    delete:
      - type: job
        labels:
          job-name: keystone-db-sync
      - type: job
        labels:
          job-name: keystone-db-init
  post:
    delete: []
    create: []
  values:
    pods:
      replicas:
        api: 2
    labels:
      node_selector_key: ucp-control-plane
      node_selector_value: enabled
  dependencies:
    - ucp_keystone_htk
...
---
schema: armada/Chart/v1
metadata:
  schema: metadata/Document/v1
  name:  ucp_keystone_htk
  layeringDefinition:
    abstract: false
    layer: global
  storagePolicy: cleartext
data:
  chart_name: ucp_keystone_htk
  release: ucp_keystone_htk
  namespace: ucp_keystone_htk
  timeout: 100
  values: {}
  source:
    type: git
    location: https://github.com/openstack/openstack-helm
    subpath: helm_toolkit
    reference: e4dd1ba91a9e3c517b0f4594c70eb9a743681432
  dependencies: []
...
