---
schema: armada/Chart/v1
metadata:
  schema: metadata/Document/v1
  name: ucp-keystone-memcached
  layeringDefinition:
    abstract: false
    layer: global
  storagePolicy: cleartext
  substitutions:
    # Chart source
    - src:
        schema: pegleg/SoftwareVersions/v1
        name: software-versions
        path: .charts.ucp.memcached
      dest:
        path: .source

    # Images
    - src:
        schema: pegleg/SoftwareVersions/v1
        name: software-versions
        path: .images.ucp.memcached
      dest:
        path: .values.images.tags

    - src:
        schema: EndpointCatalogue/v1
        name: ucp_endpoints
        path: .ucp.oslo_cache
      dest:
        path: .values.endpoints.oslo_cache
data:
  chart_name: ucp-keystone-memcached
  release: ucp-keystone-memcached
  namespace: ucp
  install:
    no_hooks: false
  upgrade:
    no_hooks: false
  values: {}
  dependencies:
    - ucp_memcached_htk
...
---
schema: armada/Chart/v1
metadata:
  schema: metadata/Document/v1
  name: ucp_memcached_htk
  layeringDefinition:
    abstract: false
    layer: global
  storagePolicy: cleartext
data:
  chart_name: ucp_memcached_htk
  release: ucp_memcached_htk
  namespace: ucp_memcached_htk
  timeout: 100
  values: {}
  source:
    type: git
    location: https://github.com/openstack/openstack-helm
    subpath: helm_toolkit
    reference: e4dd1ba91a9e3c517b0f4594c70eb9a743681432
  dependencies: []
...
