---
schema: pegleg/SoftwareVersions/v1
metadata:
  schema: metadata/Document/v1
  name: software-versions
  layeringDefinition:
    abstract: false
    layer: global
  storagePolicy: cleartext
data:
  charts:
    dependencies:
      osh-helm-toolkit:
        type: git
        location: https://git.openstack.org/openstack/openstack-helm-infra
        subpath: helm-toolkit
        reference: master
      ucp-helm-toolkit:
        type: git
        location: https://git.openstack.org/openstack/openstack-helm
        subpath: helm-toolkit
        reference: master
    calico:
      etcd:
        type: git
        location: https://github.com/att-comdev/promenade
        subpath: charts/etcd
        reference: master
      calico:
        type: git
        location: https://github.com/att-comdev/promenade
        subpath: charts/calico
        reference: master
    kubernetes:
      apiserver:
        type: git
        location: https://github.com/att-comdev/promenade
        subpath: charts/apiserver
        reference: master
      controller-manager:
        type: git
        location: https://github.com/att-comdev/promenade
        subpath: charts/controller_manager
        reference: master
      coredns:
        type: git
        location: https://github.com/att-comdev/promenade
        subpath: charts/coredns
        reference: master
      haproxy:
        type: local
        location: /etc/genesis/armada/assets/charts
        subpath: haproxy        
      etcd:
        type: git
        location: https://github.com/att-comdev/promenade
        subpath: charts/etcd
        reference: master
      ingress:
        type: git
        location: https://github.com/openstack/openstack-helm
        subpath: ingress
        reference: master
      proxy:
        type: git
        location: https://github.com/att-comdev/promenade
        subpath: charts/proxy
        reference: master
      scheduler:
        type: git
        location: https://github.com/att-comdev/promenade
        subpath: charts/scheduler
        reference: master
    osh: {}
    ucp:
      armada:
        type: git
        location: https://github.com/att-comdev/armada
        subpath: charts/armada
        reference: master
      barbican:
        type: git
        location: https://git.openstack.org/openstack/openstack-helm
        subpath: barbican
        reference: master
      ceph:
        type: git
        location: https://git.openstack.org/openstack/openstack-helm
        subpath: ceph
        reference: master
      deckhand:
        type: git
        location: https://github.com/att-comdev/deckhand
        subpath: charts/deckhand
        reference: master
      drydock:
        type: git
        location: https://github.com/att-comdev/drydock
        subpath: charts/drydock
        reference: master
      ingress:
        type: git
        location: https://github.com/openstack/openstack-helm
        subpath: ingress
        reference: master
      postgresql:
        type: git
        location: https://git.openstack.org/openstack/openstack-helm
        subpath: postgresql
        reference: master
      promenade:
        type: git
        location: https://github.com/att-comdev/promenade
        subpath: charts/promenade
        reference: master
      keystone:
        type: git
        location: https://git.openstack.org/openstack/openstack-helm
        subpath: keystone
        reference: master
      maas:
        type: git
        location: https://github.com/att-comdev/maas
        subpath: charts/maas
        reference: master
      mariadb:
        type: git
        location: https://git.openstack.org/openstack/openstack-helm
        subpath: mariadb
        reference: master
      memcached:
        type: git
        location: https://git.openstack.org/openstack/openstack-helm
        subpath: memcached
        reference: master
      rabbitmq:
        type: git
        location: https://git.openstack.org/openstack/openstack-helm
        subpath: rabbitmq
        reference: master
      rabbitmq-etcd:
        type: git
        location: https://git.openstack.org/openstack/openstack-helm
        subpath: etcd
        reference: master
      shipyard:
        type: git
        location: https://github.com/att-comdev/shipyard
        subpath: charts/shipyard
        reference: master
      tiller:
        type: git
        location: https://github.com/att-comdev/armada
        subpath: charts/tiller
        reference: master
  files:
    kubelet: https://dl.k8s.io/v1.8.6/kubernetes-node-linux-amd64.tar.gz
    
  images:
    ucp:
      armada:
        api: quay.io/attcomdev/armada:399958.2
        dep_check: quay.io/stackanetes/kubernetes-entrypoint:v0.2.1
        ks_endpoints: docker.io/kolla/ubuntu-source-heat-engine:3.0.3
        ks_service: docker.io/kolla/ubuntu-source-heat-engine:3.0.3
        ks_user: docker.io/kolla/ubuntu-source-heat-engine:3.0.3
        helm: lachlanevenson/k8s-helm:v2.7.2
        tiller: gcr.io/kubernetes-helm/tiller:v2.7.2
      promenade:
        dep_check: quay.io/stackanetes/kubernetes-entrypoint:v0.2.1
        promenade: artifacts-aic.atlantafoundry.com/ucp/promenade@sha256:eca5fce41af35be649610df922e936d12ea08d5b33e9f1b66e4e3fd59ecd3d0a
        ks_user: docker.io/kolla/ubuntu-source-heat-engine:3.0.3
        ks_service: docker.io/kolla/ubuntu-source-heat-engine:3.0.3
        ks_endpoints: docker.io/kolla/ubuntu-source-heat-engine:3.0.3
      deckhand:
        deckhand: artifacts-aic.atlantafoundry.com/ucp/deckhand@sha256:deda768765a77e7ac944075ea81ac43e84c9b2cf98cb782ba4d72aec669a6073
        dep_check: quay.io/stackanetes/kubernetes-entrypoint:v0.2.1
        db_init: docker.io/postgres:9.5
        db_sync: docker.io/postgres:9.5
        ks_endpoints: docker.io/kolla/ubuntu-source-heat-engine:3.0.3
        ks_service: docker.io/kolla/ubuntu-source-heat-engine:3.0.3
        ks_user: docker.io/kolla/ubuntu-source-heat-engine:3.0.3
      barbican:
        bootstrap: docker.io/kolla/ubuntu-source-heat-engine:3.0.3
        dep_check: quay.io/stackanetes/kubernetes-entrypoint:v0.2.1
        scripted_test: docker.io/kolla/ubuntu-source-heat-engine:3.0.3
        db_init: docker.io/kolla/ubuntu-source-heat-engine:3.0.3
        barbican_db_sync: docker.io/kolla/ubuntu-source-barbican-api:3.0.3
        db_drop: docker.io/kolla/ubuntu-source-heat-engine:3.0.3
        ks_endpoints: docker.io/kolla/ubuntu-source-heat-engine:3.0.3
        ks_service: docker.io/kolla/ubuntu-source-heat-engine:3.0.3
        ks_user: docker.io/kolla/ubuntu-source-heat-engine:3.0.3
        barbican_api: docker.io/kolla/ubuntu-source-barbican-api:3.0.3
      drydock:
        drydock: artifacts-aic.atlantafoundry.com/ucp/drydock@sha256:ad764656578d030138f5ed9dd8b0314aecd8fb0f7ff90f5fb073f55c35488eba
        dep_check: quay.io/stackanetes/kubernetes-entrypoint:v0.2.1
        ks_endpoints: docker.io/kolla/ubuntu-source-heat-engine:3.0.3
        ks_service: docker.io/kolla/ubuntu-source-heat-engine:3.0.3
        ks_user: docker.io/kolla/ubuntu-source-heat-engine:3.0.3
        drydock_db_init: docker.io/postgres:9.5
        drydock_db_sync: artifacts-aic.atlantafoundry.com/ucp/drydock@sha256:ad764656578d030138f5ed9dd8b0314aecd8fb0f7ff90f5fb073f55c35488eba
      shipyard:
        airflow: artifacts-aic.atlantafoundry.com/ucp/airflow@sha256:c9a1ccaf952e86f00d4139c00307563fb4da0ba62d91540b692a384496f47c3d
        shipyard: artifacts-aic.atlantafoundry.com/ucp/shipyard@sha256:bb3d38df7c1f5b5646d6fb5e3d8fdb1b14417d1020bb083ba0d5fedc5f022eb2
        dep_check: quay.io/stackanetes/kubernetes-entrypoint:v0.2.1
        shipyard_db_init: docker.io/postgres:9.5
        shipyard_db_sync: artifacts-aic.atlantafoundry.com/ucp/shipyard@sha256:bb3d38df7c1f5b5646d6fb5e3d8fdb1b14417d1020bb083ba0d5fedc5f022eb2
        airflow_db_init: docker.io/postgres:9.5
        airflow_db_sync: artifacts-aic.atlantafoundry.com/ucp/airflow@sha256:c9a1ccaf952e86f00d4139c00307563fb4da0ba62d91540b692a384496f47c3d
        ks_user: docker.io/kolla/ubuntu-source-heat-engine:3.0.3
        ks_service: docker.io/kolla/ubuntu-source-heat-engine:3.0.3
        ks_endpoints: docker.io/kolla/ubuntu-source-heat-engine:3.0.3
      maas:
        db_init: docker.io/postgres:9.5
        db_sync: artifacts-aic.atlantafoundry.com/ucp/maas/maas-region-controller@sha256:96b6996178d05147fdfab4e98f1eba4118d0135ff7b65d8a28a5b24fbbddf23d
        maas_rack: artifacts-aic.atlantafoundry.com/ucp/maas/maas-rack-controller@sha256:db3645f0da061507eaf5a04676aa613b6a8efd13751537eec05532c646ae5b20
        maas_region: artifacts-aic.atlantafoundry.com/ucp/maas/maas-region-controller@sha256:96b6996178d05147fdfab4e98f1eba4118d0135ff7b65d8a28a5b24fbbddf23d
        bootstrap: artifacts-aic.atlantafoundry.com/ucp/maas/maas-region-controller@sha256:96b6996178d05147fdfab4e98f1eba4118d0135ff7b65d8a28a5b24fbbddf23d
        export_api_key: artifacts-aic.atlantafoundry.com/ucp/maas/maas-region-controller@sha256:96b6996178d05147fdfab4e98f1eba4118d0135ff7b65d8a28a5b24fbbddf23d
        maas_cache: artifacts-aic.atlantafoundry.com/ucp/maas/sstream-cache@sha256:930d74cf99a6802edd1c85a0839477365903631dc8fc2e1bb2bfc07be74d6a30
        dep_check: quay.io/stackanetes/kubernetes-entrypoint:v0.2.1
      keystone:
        keystone_bootstrap: docker.io/kolla/ubuntu-source-keystone:3.0.3
        test: docker.io/kolla/ubuntu-source-rally:4.0.0
        db_init: docker.io/kolla/ubuntu-source-heat-engine:3.0.3
        keystone_db_sync: docker.io/kolla/ubuntu-source-keystone:3.0.3
        db_drop: docker.io/kolla/ubuntu-source-heat-engine:3.0.3
        keystone_fernet_setup: docker.io/kolla/ubuntu-source-keystone:3.0.3
        keystone_fernet_rotate: docker.io/kolla/ubuntu-source-keystone:3.0.3
        keystone_credential_setup: docker.io/kolla/ubuntu-source-keystone:3.0.3
        keystone_credential_rotate: docker.io/kolla/ubuntu-source-keystone:3.0.3
        keystone_api: docker.io/kolla/ubuntu-source-keystone:3.0.3
        dep_check: quay.io/stackanetes/kubernetes-entrypoint:v0.2.1
      tiller:
        tiller: gcr.io/kubernetes-helm/tiller:v2.7.2
      mariadb:
        mariadb: docker.io/mariadb:10.1.23
        dep_check: quay.io/stackanetes/kubernetes-entrypoint:v0.2.1
      postgresql:
        postgresql: docker.io/postgres:9.5
        dep_check: quay.io/stackanetes/kubernetes-entrypoint:v0.2.1
      memcached:
        memcached: docker.io/memcached:1.5.5
        dep_check: quay.io/stackanetes/kubernetes-entrypoint:v0.2.1
      rabbitmq:
        rabbitmq: docker.io/rabbitmq:3.7
        dep_check: quay.io/stackanetes/kubernetes-entrypoint:v0.2.1
    ceph:
      ceph:
        ks_endpoints: docker.io/kolla/ubuntu-source-heat-engine:3.0.3
        ks_service: docker.io/kolla/ubuntu-source-heat-engine:3.0.3
        ks_user: docker.io/kolla/ubuntu-source-heat-engine:3.0.3
        ceph_bootstrap: docker.io/ceph/daemon:tag-build-master-luminous-ubuntu-16.04
        dep_check: quay.io/stackanetes/kubernetes-entrypoint:v0.2.1
        ceph_daemon: docker.io/ceph/daemon:tag-build-master-luminous-ubuntu-16.04
        ceph_config_helper: docker.io/port/ceph-config-helper:v1.7.5
        ceph_rbd_provisioner: quay.io/external_storage/rbd-provisioner:v0.1.1
        ceph_cephfs_provisioner: quay.io/external_storage/cephfs-provisioner:v0.1.1
    kubernetes:
      apiserver:
        anchor: gcr.io/google_containers/hyperkube-amd64:v1.8.6
        apiserver: gcr.io/google_containers/hyperkube-amd64:v1.8.6
        dep_check: quay.io/stackanetes/kubernetes-entrypoint:v0.2.1
      controller-manager:
        anchor: gcr.io/google_containers/hyperkube-amd64:v1.8.6
        controller_manager: gcr.io/google_containers/hyperkube-amd64:v1.8.6
        dep_check: quay.io/stackanetes/kubernetes-entrypoint:v0.2.1
      coredns:
        coredns: coredns/coredns:1.0.5
      haproxy:
        haproxy: haproxy:1.8.3
        anchor: gcr.io/google_containers/hyperkube-amd64:v1.8.6
      etcd:
        etcd: quay.io/coreos/etcd:v3.2.14
        etcdctl: quay.io/coreos/etcd:v3.2.14
      kubectl: gcr.io/google_containers/hyperkube-amd64:v1.8.6
      pause: gcr.io/google_containers/pause-amd64:3.0
      scheduler:
        anchor: gcr.io/google_containers/hyperkube-amd64:v1.8.6
        scheduler: gcr.io/google_containers/hyperkube-amd64:v1.8.6
      proxy:
        proxy: gcr.io/google_containers/hyperkube-amd64:v1.8.6
    calico:
      etcd:
        etcd: quay.io/coreos/etcd:v3.2.14
        etcdctl: quay.io/coreos/etcd:v3.2.14
      calico:
        cni: quay.io/calico/cni:v1.11.2
        ctl: quay.io/calico/ctl:v1.6.3
        node: quay.io/calico/node:v2.6.5
        policy_controller: quay.io/calico/kube-controllers:v1.0.2
  packages:
    repositories:
      - name: docker
        url: http://apt.dockerproject.org/repo
        distributions:
          - ubuntu-xenial
        components:
          - main
        gpgkey: |-
          -----BEGIN PGP PUBLIC KEY BLOCK-----

          mQINBFWln24BEADrBl5p99uKh8+rpvqJ48u4eTtjeXAWbslJotmC/CakbNSqOb9o
          ddfzRvGVeJVERt/Q/mlvEqgnyTQy+e6oEYN2Y2kqXceUhXagThnqCoxcEJ3+KM4R
          mYdoe/BJ/J/6rHOjq7Omk24z2qB3RU1uAv57iY5VGw5p45uZB4C4pNNsBJXoCvPn
          TGAs/7IrekFZDDgVraPx/hdiwopQ8NltSfZCyu/jPpWFK28TR8yfVlzYFwibj5WK
          dHM7ZTqlA1tHIG+agyPf3Rae0jPMsHR6q+arXVwMccyOi+ULU0z8mHUJ3iEMIrpT
          X+80KaN/ZjibfsBOCjcfiJSB/acn4nxQQgNZigna32velafhQivsNREFeJpzENiG
          HOoyC6qVeOgKrRiKxzymj0FIMLru/iFF5pSWcBQB7PYlt8J0G80lAcPr6VCiN+4c
          NKv03SdvA69dCOj79PuO9IIvQsJXsSq96HB+TeEmmL+xSdpGtGdCJHHM1fDeCqkZ
          hT+RtBGQL2SEdWjxbF43oQopocT8cHvyX6Zaltn0svoGs+wX3Z/H6/8P5anog43U
          65c0A+64Jj00rNDr8j31izhtQMRo892kGeQAaaxg4Pz6HnS7hRC+cOMHUU4HA7iM
          zHrouAdYeTZeZEQOA7SxtCME9ZnGwe2grxPXh/U/80WJGkzLFNcTKdv+rwARAQAB
          tDdEb2NrZXIgUmVsZWFzZSBUb29sIChyZWxlYXNlZG9ja2VyKSA8ZG9ja2VyQGRv
          Y2tlci5jb20+iQI4BBMBAgAiBQJVpZ9uAhsvBgsJCAcDAgYVCAIJCgsEFgIDAQIe
          AQIXgAAKCRD3YiFXLFJgnbRfEAC9Uai7Rv20QIDlDogRzd+Vebg4ahyoUdj0CH+n
          Ak40RIoq6G26u1e+sdgjpCa8jF6vrx+smpgd1HeJdmpahUX0XN3X9f9qU9oj9A4I
          1WDalRWJh+tP5WNv2ySy6AwcP9QnjuBMRTnTK27pk1sEMg9oJHK5p+ts8hlSC4Sl
          uyMKH5NMVy9c+A9yqq9NF6M6d6/ehKfBFFLG9BX+XLBATvf1ZemGVHQusCQebTGv
          0C0V9yqtdPdRWVIEhHxyNHATaVYOafTj/EF0lDxLl6zDT6trRV5n9F1VCEh4Aal8
          L5MxVPcIZVO7NHT2EkQgn8CvWjV3oKl2GopZF8V4XdJRl90U/WDv/6cmfI08GkzD
          YBHhS8ULWRFwGKobsSTyIvnbk4NtKdnTGyTJCQ8+6i52s+C54PiNgfj2ieNn6oOR
          7d+bNCcG1CdOYY+ZXVOcsjl73UYvtJrO0Rl/NpYERkZ5d/tzw4jZ6FCXgggA/Zxc
          jk6Y1ZvIm8Mt8wLRFH9Nww+FVsCtaCXJLP8DlJLASMD9rl5QS9Ku3u7ZNrr5HWXP
          HXITX660jglyshch6CWeiUATqjIAzkEQom/kEnOrvJAtkypRJ59vYQOedZ1sFVEL
          MXg2UCkD/FwojfnVtjzYaTCeGwFQeqzHmM241iuOmBYPeyTY5veF49aBJA1gEJOQ
          TvBR8Q==
          =Fm3p
          -----END PGP PUBLIC KEY BLOCK-----
    named:
      docker: docker-engine=1.13.1-0~ubuntu-xenial
      socat: socat=1.7.3.1-1
    unnamed:
      - ceph-common=10.2.9-0ubuntu0.16.04.1

