---
schema: armada/Chart/v1
metadata:
  schema: metadata/Document/v1
  name: kubernetes-etcd
  layeringDefinition:
    abstract: false
    layer: global
  storagePolicy: cleartext
  substitutions:
    # Chart source
    - src:
        schema: pegleg/SoftwareVersions/v1
        name: software-versions
        path: .charts.kubernetes.etcd
      dest:
        path: .source

    # Images
    - src:
        schema: pegleg/SoftwareVersions/v1
        name: software-versions
        path: .images.kubernetes.etcd
      dest:
        path: .values.images.tags

    # IP addresses
    -
      src:
        schema: pegleg/CommonAddresses/v1
        name: common-addresses
        path: .kubernetes.etcd_service_ip
      dest:
        path: .values.service.ip
    -
      src:
        schema: pegleg/CommonAddresses/v1
        name: common-addresses
        path: .kubernetes.etcd_service_ip
      dest:
        path: .values.anchor.etcdctl_endpoint

    # Node names
    -
      src:
        schema: pegleg/CommonAddresses/v1
        name: common-addresses
        path: .masters[0].hostname
      dest:
        path: .values.nodes[0].name
    -
      src:
        schema: pegleg/CommonAddresses/v1
        name: common-addresses
        path: .masters[1].hostname
      dest:
        path: .values.nodes[1].name
    -
      src:
        schema: pegleg/CommonAddresses/v1
        name: common-addresses
        path: .masters[2].hostname
      dest:
        path: .values.nodes[2].name
    -
      src:
        schema: pegleg/CommonAddresses/v1
        name: common-addresses
        path: .genesis.hostname
      dest:
        path: .values.nodes[3].name

    # CAs
    -
      src:
        schema: deckhand/CertificateAuthority/v1
        name: kubernetes-etcd
        path: .
      dest:
        path: .values.secrets.tls.client.ca
    -
      src:
        schema: deckhand/CertificateAuthority/v1
        name: kubernetes-etcd-peer
        path: .
      dest:
        path: .values.secrets.tls.peer.ca

    -
      src:
        schema: deckhand/Certificate/v1
        name: kubernetes-etcd-anchor
        path: .
      dest:
        path: .values.secrets.anchor.tls.cert
    -
      src:
        schema: deckhand/CertificateKey/v1
        name: kubernetes-etcd-anchor
        path: .
      dest:
        path: .values.secrets.anchor.tls.key

    # Server certs
    -
      src:
        schema: deckhand/Certificate/v1
        name: kubernetes-etcd-master0
        path: .
      dest:
        path: .values.nodes[0].tls.client.cert
    -
      src:
        schema: deckhand/CertificateKey/v1
        name: kubernetes-etcd-master0
        path: .
      dest:
        path: .values.nodes[0].tls.client.key
    -
      src:
        schema: deckhand/Certificate/v1
        name: kubernetes-etcd-master0-peer
        path: .
      dest:
        path: .values.nodes[0].tls.peer.cert
    -
      src:
        schema: deckhand/CertificateKey/v1
        name: kubernetes-etcd-master0-peer
        path: .
      dest:
        path: .values.nodes[0].tls.peer.key

    -
      src:
        schema: deckhand/Certificate/v1
        name: kubernetes-etcd-master1
        path: .
      dest:
        path: .values.nodes[1].tls.client.cert
    -
      src:
        schema: deckhand/CertificateKey/v1
        name: kubernetes-etcd-master1
        path: .
      dest:
        path: .values.nodes[1].tls.client.key
    -
      src:
        schema: deckhand/Certificate/v1
        name: kubernetes-etcd-master1-peer
        path: .
      dest:
        path: .values.nodes[1].tls.peer.cert
    -
      src:
        schema: deckhand/CertificateKey/v1
        name: kubernetes-etcd-master1-peer
        path: .
      dest:
        path: .values.nodes[1].tls.peer.key

    -
      src:
        schema: deckhand/Certificate/v1
        name: kubernetes-etcd-master2
        path: .
      dest:
        path: .values.nodes[2].tls.client.cert
    -
      src:
        schema: deckhand/CertificateKey/v1
        name: kubernetes-etcd-master2
        path: .
      dest:
        path: .values.nodes[2].tls.client.key
    -
      src:
        schema: deckhand/Certificate/v1
        name: kubernetes-etcd-master2-peer
        path: .
      dest:
        path: .values.nodes[2].tls.peer.cert
    -
      src:
        schema: deckhand/CertificateKey/v1
        name: kubernetes-etcd-master2-peer
        path: .
      dest:
        path: .values.nodes[2].tls.peer.key

    # NOTE(mb874d): Be sure we generate these certs for genesis.
    -
      src:
        schema: deckhand/Certificate/v1
        name: kubernetes-etcd-genesis
        path: .
      dest:
        path: .values.nodes[3].tls.client.cert
    -
      src:
        schema: deckhand/CertificateKey/v1
        name: kubernetes-etcd-genesis
        path: .
      dest:
        path: .values.nodes[3].tls.client.key
    -
      src:
        schema: deckhand/Certificate/v1
        name: kubernetes-etcd-genesis-peer
        path: .
      dest:
        path: .values.nodes[3].tls.peer.cert
    -
      src:
        schema: deckhand/CertificateKey/v1
        name: kubernetes-etcd-genesis-peer
        path: $
      dest:
        path: .values.nodes[3].tls.peer.key

data:
  chart_name: etcd
  release: kubernetes-etcd
  namespace: kube-system
  timeout: 600
  wait:
    timeout: 600
  upgrade:
    no_hooks: true
  values:
    labels:
      anchor:
        node_selector_key: kubernetes-etcd
        node_selector_value: enabled
    etcd:
      host_data_path: /var/lib/etcd/kubernetes
      host_etc_path: /etc/etcd/kubernetes
    service:
      name: kubernetes-etcd
    network:
      service_client:
        name: service_client
        port: 2379
        target_port: 2379
      service_peer:
        name: service_peer
        port: 2380
        target_port: 2380
  dependencies:
    - kube_etcd_htk
---
schema: armada/Chart/v1
metadata:
  schema: metadata/Document/v1
  name: kube_etcd_htk
  layeringDefinition:
    abstract: false
    layer: global
  storagePolicy: cleartext
data:
  chart_name: kube_etcd_htk
  release: kube_etcd_htk
  namespace: kube_etcd_htk
  timeout: 100
  values: {}
  source:
    type: git
    location: https://github.com/openstack/openstack-helm
    subpath: helm_toolkit
    reference: e4dd1ba91a9e3c517b0f4594c70eb9a743681432
  dependencies: []
...
