---
schema: pegleg/SoftwareVersions/v1
metadata:
  schema: metadata/Document/v1
  name: software-versions
  layeringDefinition:
    abstract: false
    layer: site
    parentSelector:
      name: software-versions-global
    actions:
      - method: merge
        path: .
  storagePolicy: cleartext
data:
  images:
    osh:
      memcached:
        dep_check: 'quay.io/stackanetes/kubernetes-entrypoint:v0.2.1'
        memcached: 'docker.io/memcached:1.5.5'
      barbican:
        bootstrap: docker.io/openstackhelm/heat:newton
        dep_check: quay.io/stackanetes/kubernetes-entrypoint:v0.2.1
        scripted_test: docker.io/openstackhelm/heat:newton
        db_init: docker.io/openstackhelm/heat:newton
        barbican_db_sync: docker.io/openstackhelm/barbican:newton
        db_drop: docker.io/openstackhelm/heat:newton
        ks_user: docker.io/openstackhelm/heat:newton
        ks_service: docker.io/openstackhelm/heat:newton
        ks_endpoints: docker.io/openstackhelm/heat:newton
        barbican_api: docker.io/openstackhelm/barbican:newton
        rabbit_init: docker.io/rabbitmq:3.7-management
      cinder:
        test: docker.io/kolla/ubuntu-source-rally:4.0.0
        db_init: docker.io/openstackhelm/heat:newton
        cinder_db_sync: docker.io/openstackhelm/cinder:newton
        db_drop: docker.io/openstackhelm/heat:newton
        ks_user: docker.io/openstackhelm/heat:newton
        ks_service: docker.io/openstackhelm/heat:newton
        ks_endpoints: docker.io/openstackhelm/heat:newton
        cinder_api: docker.io/openstackhelm/cinder:newton
        bootstrap: docker.io/openstackhelm/heat:newton
        cinder_scheduler: docker.io/openstackhelm/cinder:newton
        cinder_volume: docker.io/openstackhelm/cinder:newton
        cinder_volume_usage_audit: docker.io/openstackhelm/cinder:newton
        cinder_storage_init: docker.io/ceph/daemon:tag-build-master-luminous-ubuntu-16.04
        cinder_backup: docker.io/openstackhelm/cinder:newton
        cinder_backup_storage_init: docker.io/ceph/daemon:tag-build-master-luminous-ubuntu-16.04
        dep_check: quay.io/stackanetes/kubernetes-entrypoint:v0.2.1
        rabbit_init: docker.io/rabbitmq:3.7-management
      glance:
        test: docker.io/kolla/ubuntu-source-rally:4.0.0
        glance_storage_init: docker.io/ceph/daemon:tag-build-master-luminous-ubuntu-16.04
        db_init: docker.io/openstackhelm/heat:newton
        glance_db_sync: docker.io/openstackhelm/glance:newton
        db_drop: docker.io/openstackhelm/heat:newton
        ks_user: docker.io/openstackhelm/heat:newton
        ks_service: docker.io/openstackhelm/heat:newton
        ks_endpoints: docker.io/openstackhelm/heat:newton
        glance_api: docker.io/openstackhelm/glance:newton
        glance_registry: docker.io/openstackhelm/glance:newton
        # Bootstrap image requires curl
        bootstrap: docker.io/openstackhelm/heat:newton
        dep_check: quay.io/stackanetes/kubernetes-entrypoint:v0.2.1
        rabbit_init: docker.io/rabbitmq:3.7-management
      heat:
        bootstrap: docker.io/openstackhelm/heat:newton
        db_init: docker.io/openstackhelm/heat:newton
        heat_db_sync: docker.io/openstackhelm/heat:newton
        db_drop: docker.io/openstackhelm/heat:newton
        ks_user: docker.io/openstackhelm/heat:newton
        ks_service: docker.io/openstackhelm/heat:newton
        ks_endpoints: docker.io/openstackhelm/heat:newton
        heat_api: docker.io/openstackhelm/heat:newton
        heat_cfn: docker.io/openstackhelm/heat:newton
        heat_cloudwatch: docker.io/openstackhelm/heat:newton
        heat_engine: docker.io/openstackhelm/heat:newton
        heat_engine_cleaner: docker.io/openstackhelm/heat:newton
        dep_check: quay.io/stackanetes/kubernetes-entrypoint:v0.2.1
        rabbit_init: docker.io/rabbitmq:3.7-management
      horizon:
        db_init: docker.io/openstackhelm/heat:newton
        horizon_db_sync: docker.io/openstackhelm/horizon:newton
        db_drop: docker.io/openstackhelm/heat:newton
        horizon: docker.io/openstackhelm/horizon:newton
        dep_check: quay.io/stackanetes/kubernetes-entrypoint:v0.2.1
      ingress:
        entrypoint: quay.io/stackanetes/kubernetes-entrypoint:v0.2.1
        ingress: quay.io/kubernetes-ingress-controller/nginx-ingress-controller:0.9.0
        error_pages: gcr.io/google_containers/defaultbackend:1.0
        dep_check: quay.io/stackanetes/kubernetes-entrypoint:v0.2.1
      keystone:
        bootstrap: docker.io/openstackhelm/heat:newton
        test: docker.io/kolla/ubuntu-source-rally:4.0.0
        db_init: docker.io/openstackhelm/heat:newton
        keystone_db_sync: docker.io/openstackhelm/keystone:newton
        db_drop: docker.io/openstackhelm/heat:newton
        ks_user: docker.io/openstackhelm/heat:newton
        keystone_fernet_setup: docker.io/openstackhelm/keystone:newton
        keystone_fernet_rotate: docker.io/openstackhelm/keystone:newton
        keystone_credential_setup: docker.io/openstackhelm/keystone:newton
        keystone_credential_rotate: docker.io/openstackhelm/keystone:newton
        keystone_api: docker.io/openstackhelm/keystone:newton
        keystone_domain_manage: docker.io/openstackhelm/keystone:newton
        dep_check: quay.io/stackanetes/kubernetes-entrypoint:v0.2.1
        rabbit_init: docker.io/rabbitmq:3.7-management
      libvirt:
        libvirt: docker.io/openstackhelm/libvirt:ubuntu-xenial-1.3.1
        dep_check: quay.io/stackanetes/kubernetes-entrypoint:v0.2.1
      mariadb:
        mariadb: docker.io/mariadb:10.1.23
        prometheus_create_mysql_user: docker.io/mariadb:10.1.23
        prometheus_mysql_exporter: docker.io/prom/mysqld-exporter:v0.10.0
        prometheus_mysql_exporter_helm_tests: docker.io/openstackhelm/heat:newton
        dep_check: quay.io/stackanetes/kubernetes-entrypoint:v0.2.1
      neutron:
        bootstrap: docker.io/openstackhelm/heat:newton
        test: docker.io/kolla/ubuntu-source-rally:4.0.0
        db_init: docker.io/openstackhelm/heat:newton
        neutron_db_sync: docker.io/openstackhelm/neutron:newton
        db_drop: docker.io/openstackhelm/heat:newton
        ks_user: docker.io/openstackhelm/heat:newton
        ks_service: docker.io/openstackhelm/heat:newton
        ks_endpoints: docker.io/openstackhelm/heat:newton
        neutron_server: docker.io/openstackhelm/neutron:newton
        neutron_dhcp: docker.io/openstackhelm/neutron:newton
        neutron_metadata: docker.io/openstackhelm/neutron:newton
        neutron_l3: docker.io/openstackhelm/neutron:newton
        neutron_openvswitch_agent: docker.io/openstackhelm/neutron:newton
        neutron_linuxbridge_agent: docker.io/openstackhelm/neutron:newton
        dep_check: quay.io/stackanetes/kubernetes-entrypoint:v0.2.1
        rabbit_init: docker.io/rabbitmq:3.7-management
      nova:
        bootstrap: docker.io/openstackhelm/heat:newton
        db_drop: docker.io/openstackhelm/heat:newton
        db_init: docker.io/openstackhelm/heat:newton
        dep_check: 'quay.io/stackanetes/kubernetes-entrypoint:v0.2.1'
        ks_user: docker.io/openstackhelm/heat:newton
        ks_service: docker.io/openstackhelm/heat:newton
        ks_endpoints: docker.io/openstackhelm/heat:newton
        nova_api: docker.io/openstackhelm/nova:newton
        nova_cell_setup: docker.io/openstackhelm/nova:newton
        nova_compute: docker.io/openstackhelm/nova:newton
        nova_compute_ironic: 'docker.io/kolla/ubuntu-source-nova-compute-ironic:3.0.3'
        nova_compute_ssh: docker.io/openstackhelm/nova:newton
        nova_conductor: docker.io/openstackhelm/nova:newton
        nova_consoleauth: docker.io/openstackhelm/nova:newton
        nova_db_sync: docker.io/openstackhelm/nova:newton
        nova_novncproxy: docker.io/openstackhelm/nova:newton
        nova_novncproxy_assets: 'docker.io/kolla/ubuntu-source-nova-novncproxy:3.0.3'
        nova_placement: docker.io/openstackhelm/nova:newton
        nova_scheduler: docker.io/openstackhelm/nova:newton
        nova_spiceproxy: docker.io/openstackhelm/nova:newton
        nova_spiceproxy_assets: 'docker.io/kolla/ubuntu-source-nova-spicehtml5proxy:3.0.3'
        test: 'docker.io/kolla/ubuntu-source-rally:4.0.0'
        rabbit_init: docker.io/rabbitmq:3.7-management
      openvswitch:
        openvswitch_db_server: docker.io/openstackhelm/openvswitch:v2.8.1
        openvswitch_vswitchd: docker.io/openstackhelm/openvswitch:v2.8.1
        dep_check: quay.io/stackanetes/kubernetes-entrypoint:v0.2.1
      rabbitmq:
        prometheus_rabbitmq_exporter: docker.io/kbudde/rabbitmq-exporter:v0.21.0
        prometheus_rabbitmq_exporter_helm_tests: docker.io/openstackhelm/heat:newton
        rabbitmq: docker.io/rabbitmq:3.7
        dep_check: quay.io/stackanetes/kubernetes-entrypoint:v0.2.1
    osh_infra:
      elasticsearch:
        apache_proxy: docker.io/httpd:2.4
        memory_init: docker.io/kolla/ubuntu-source-heat-engine:3.0.3
        curator:  docker.io/bobrik/curator:5.2.0
        elasticsearch: docker.io/elasticsearch:5.6.4
        helm_tests: docker.io/kolla/ubuntu-source-heat-engine:3.0.3
        prometheus_elasticsearch_exporter: docker.io/justwatch/elasticsearch_exporter:1.0.1
        dep_check: quay.io/stackanetes/kubernetes-entrypoint:v0.2.1
        snapshot_repository: docker.io/kolla/ubuntu-source-heat-engine:3.0.3
        image_repo_sync: docker.io/docker:17.07.0
      fluent_logging:
        fluentbit: docker.io/fluent/fluent-bit:0.12.14
        fluentd: docker.io/kolla/ubuntu-source-fluentd:ocata
        prometheus_fluentd_exporter: docker.io/srwilkers/fluentd_exporter:v0.1
        dep_check: quay.io/stackanetes/kubernetes-entrypoint:v0.2.1
        helm_tests: docker.io/kolla/ubuntu-source-heat-engine:3.0.3
        elasticsearch_template: docker.io/kolla/ubuntu-source-heat-engine:3.0.3
        image_repo_sync: docker.io/docker:17.07.0
      kibana:
        apache_proxy: docker.io/httpd:2.4
        kibana: docker.io/kibana:5.6.4
        dep_check: quay.io/stackanetes/kubernetes-entrypoint:v0.2.1
        image_repo_sync: docker.io/docker:17.07.0
      prometheus:
        prometheus: docker.io/prom/prometheus:v2.0.0
        helm_tests: docker.io/kolla/ubuntu-source-heat-engine:3.0.3
        dep_check: quay.io/stackanetes/kubernetes-entrypoint:v0.2.1
        image_repo_sync: docker.io/docker:17.07.0
      prometheus_node_exporter:
        node_exporter: docker.io/prom/node-exporter:v0.15.0
        dep_check: quay.io/stackanetes/kubernetes-entrypoint:v0.2.1
        image_repo_sync: docker.io/docker:17.07.0
      prometheus_kube_state_metrics:
        kube_state_metrics: quay.io/coreos/kube-state-metrics:v1.2.0
        dep_check: quay.io/stackanetes/kubernetes-entrypoint:v0.2.1
        image_repo_sync: docker.io/docker:17.07.0
      prometheus_alertmanager:
        alertmanager: docker.io/prom/alertmanager:v0.11.0
        dep_check: quay.io/stackanetes/kubernetes-entrypoint:v0.2.1
        image_repo_sync: docker.io/docker:17.07.0
      prometheus_openstack_exporter:
        prometheus_openstack_exporter: docker.io/rakeshpatnaik/prometheus-openstack-exporter:v0.1
        dep_check: quay.io/stackanetes/kubernetes-entrypoint:v0.2.1
        image_repo_sync: docker.io/docker:17.07.0
        ks_user: docker.io/kolla/ubuntu-source-heat-engine:3.0.3
      grafana:
        grafana: docker.io/grafana/grafana:4.5.2
        datasource: docker.io/kolla/ubuntu-source-heat-engine:3.0.3
        dep_check: quay.io/stackanetes/kubernetes-entrypoint:v0.2.1
        db_init: docker.io/kolla/ubuntu-source-heat-engine:3.0.3
        grafana_db_session_sync: docker.io/kolla/ubuntu-source-heat-engine:3.0.3
        image_repo_sync: docker.io/docker:17.07.0
    ucp:
      armada:
        # git 7a2ba22ab12a3f1f180b6af4085972ba44853377
        dep_check: quay.io/stackanetes/kubernetes-entrypoint:v0.2.1
        ks_endpoints: docker.io/kolla/ubuntu-source-heat-engine:3.0.3
        ks_service: docker.io/kolla/ubuntu-source-heat-engine:3.0.3
        ks_user: docker.io/kolla/ubuntu-source-heat-engine:3.0.3
        helm: lachlanevenson/k8s-helm:v2.7.2
        tiller: gcr.io/kubernetes-helm/tiller:v2.7.0
      promenade:
        # git 86c3c11ba47e12a4db74ebaf7e917a48abcc030d
        dep_check: quay.io/stackanetes/kubernetes-entrypoint:v0.2.1
        ks_user: docker.io/kolla/ubuntu-source-heat-engine:3.0.3
        ks_service: docker.io/kolla/ubuntu-source-heat-engine:3.0.3
        ks_endpoints: docker.io/kolla/ubuntu-source-heat-engine:3.0.3
      deckhand:
        # git 86ae1ba9ee9a6a5ad4ff92d17fcd7e57fe1bb5d2
        dep_check: quay.io/stackanetes/kubernetes-entrypoint:v0.2.1
        db_init: docker.io/postgres:9.5
        db_sync: docker.io/postgres:9.5
        ks_endpoints: docker.io/kolla/ubuntu-source-heat-engine:3.0.3
        ks_service: docker.io/kolla/ubuntu-source-heat-engine:3.0.3
        ks_user: docker.io/kolla/ubuntu-source-heat-engine:3.0.3
      barbican:
        bootstrap: docker.io/kolla/ubuntu-source-heat-engine:3.0.3
        dep_check: quay.io/stackanetes/kubernetes-entrypoint:v0.2.1
        scripted_test: docker.io/kolla/ubuntu-source-heat-engine:3.0.3
        db_init: docker.io/kolla/ubuntu-source-heat-engine:3.0.3
        barbican_db_sync: docker.io/kolla/ubuntu-source-barbican-api:3.0.3
        db_drop: docker.io/kolla/ubuntu-source-heat-engine:3.0.3
        ks_endpoints: docker.io/kolla/ubuntu-source-heat-engine:3.0.3
        ks_service: docker.io/kolla/ubuntu-source-heat-engine:3.0.3
        ks_user: docker.io/kolla/ubuntu-source-heat-engine:3.0.3
        barbican_api: docker.io/kolla/ubuntu-source-barbican-api:3.0.3
      drydock:
        # git refs/changes/62/402962/1
        dep_check: quay.io/stackanetes/kubernetes-entrypoint:v0.2.1
        ks_user: docker.io/kolla/ubuntu-source-heat-engine:3.0.3
        ks_service: docker.io/kolla/ubuntu-source-heat-engine:3.0.3
        ks_endpoints: docker.io/kolla/ubuntu-source-heat-engine:3.0.3
        drydock_db_init: docker.io/postgres:9.5
      shipyard:
        # git 7046ad34ed7c30871be9918c6cace7a4839bceb4
        dep_check: quay.io/stackanetes/kubernetes-entrypoint:v0.2.1
        shipyard_db_init: docker.io/postgres:9.5
        airflow_db_init: docker.io/postgres:9.5
        ks_user: docker.io/kolla/ubuntu-source-heat-engine:3.0.3
        ks_service: docker.io/kolla/ubuntu-source-heat-engine:3.0.3
        ks_endpoints: docker.io/kolla/ubuntu-source-heat-engine:3.0.3
      maas:
        # git bde0e4260e0e68c7d1a72b100e499b655f4238c0
        db_init: docker.io/postgres:9.5
        dep_check: quay.io/stackanetes/kubernetes-entrypoint:v0.2.1
      keystone:
        keystone_bootstrap: docker.io/kolla/ubuntu-source-keystone:3.0.3
        test: docker.io/kolla/ubuntu-source-rally:4.0.0
        db_init: docker.io/kolla/ubuntu-source-heat-engine:3.0.3
        keystone_db_sync: docker.io/kolla/ubuntu-source-keystone:3.0.3
        db_drop: docker.io/kolla/ubuntu-source-heat-engine:3.0.3
        keystone_fernet_setup: docker.io/kolla/ubuntu-source-keystone:3.0.3
        keystone_fernet_rotate: docker.io/kolla/ubuntu-source-keystone:3.0.3
        keystone_credential_setup: docker.io/kolla/ubuntu-source-keystone:3.0.3
        keystone_credential_rotate: docker.io/kolla/ubuntu-source-keystone:3.0.3
        keystone_api: docker.io/kolla/ubuntu-source-keystone:3.0.3
        dep_check: quay.io/stackanetes/kubernetes-entrypoint:v0.2.1
      tiller:
        tiller: gcr.io/kubernetes-helm/tiller:v2.7.2
      mariadb:
        mariadb: docker.io/mariadb:10.1.23
        dep_check: quay.io/stackanetes/kubernetes-entrypoint:v0.2.1
      postgresql:
        postgresql: docker.io/postgres:9.5
        dep_check: quay.io/stackanetes/kubernetes-entrypoint:v0.2.1
      memcached:
        memcached: docker.io/memcached:1.5.5
        dep_check: quay.io/stackanetes/kubernetes-entrypoint:v0.2.1
      rabbitmq:
        rabbitmq: docker.io/rabbitmq:3.7
        dep_check: quay.io/stackanetes/kubernetes-entrypoint:v0.2.1
    ceph:
      ceph:
        ks_endpoints: docker.io/kolla/ubuntu-source-heat-engine:3.0.3
        ks_service: docker.io/kolla/ubuntu-source-heat-engine:3.0.3
        ks_user: docker.io/kolla/ubuntu-source-heat-engine:3.0.3
        ceph_bootstrap: docker.io/ceph/daemon:tag-build-master-luminous-ubuntu-16.04
        dep_check: quay.io/stackanetes/kubernetes-entrypoint:v0.2.1
        ceph_daemon: docker.io/ceph/daemon:tag-build-master-luminous-ubuntu-16.04
        ceph_config_helper: docker.io/port/ceph-config-helper:v1.7.5
        ceph_rbd_provisioner: quay.io/external_storage/rbd-provisioner:v0.1.1
        ceph_cephfs_provisioner: quay.io/external_storage/cephfs-provisioner:v0.1.1
    kubernetes:
      apiserver:
        anchor: gcr.io/google_containers/hyperkube-amd64:v1.8.6
        apiserver: gcr.io/google_containers/hyperkube-amd64:v1.8.6
        dep_check: quay.io/stackanetes/kubernetes-entrypoint:v0.2.1
      controller-manager:
        anchor: gcr.io/google_containers/hyperkube-amd64:v1.8.6
        controller_manager: gcr.io/google_containers/hyperkube-amd64:v1.8.6
        dep_check: quay.io/stackanetes/kubernetes-entrypoint:v0.2.1
      coredns:
        coredns: coredns/coredns:1.0.5
      haproxy:
        haproxy: haproxy:1.8.3
        anchor: gcr.io/google_containers/hyperkube-amd64:v1.8.6
      etcd:
        etcd: quay.io/coreos/etcd:v3.2.14
        etcdctl: quay.io/coreos/etcd:v3.2.14
      kubectl: gcr.io/google_containers/hyperkube-amd64:v1.8.6
      pause: gcr.io/google_containers/pause-amd64:3.0
      scheduler:
        anchor: gcr.io/google_containers/hyperkube-amd64:v1.8.6
        scheduler: gcr.io/google_containers/hyperkube-amd64:v1.8.6
      proxy:
        proxy: gcr.io/google_containers/hyperkube-amd64:v1.8.6
    calico:
      etcd:
        etcd: quay.io/coreos/etcd:v3.2.14
        etcdctl: quay.io/coreos/etcd:v3.2.14
      calico:
        cni: quay.io/calico/cni:v1.11.2
        ctl: quay.io/calico/ctl:v1.6.3
        node: quay.io/calico/node:v2.6.5
        policy_controller: quay.io/calico/kube-controllers:v1.0.2
...
