---
schema: pegleg/AccountCatalogue/v1
metadata:
  schema: metadata/Document/v1
  name: ucp_service_accounts
  layeringDefinition:
    abstract: false
    layer: global
  storagePolicy: cleartext
data:
  ucp:
    postgres:
      admin:
        username: postgres
    oslo_db:
      admin:
        username: root
    oslo_messaging:
      admin:
        username: rabbitmq
    keystone:
      admin:
        region_name: RegionOne
        username: admin
        project_name: admin
        user_domain_name: default
        project_domain_name: default
      oslo_messaging:
        admin:
          username: rabbitmq
        keystone:
          username: keystone
      oslo_db:
        username: keystone
        database: keystone
    promenade:
      keystone:
        region_name: RegionOne
        role: admin
        project_name: service
        project_domain_name: default
        user_domain_name: default
        username: promenade
    drydock:
      keystone:
        region_name: RegionOne
        role: admin
        project_name: service
        project_domain_name: default
        user_domain_name: default
        username: drydock
      postgres:
        username: drydock
        database: drydock
    shipyard:
      keystone:
        region_name: RegionOne
        role: admin
        project_name: service
        project_domain_name: default
        user_domain_name: default
        username: shipyard
      postgres:
        username: shipyard
        database: shipyard
    airflow:
      postgres:
        username: airflow
        database: airflow
      oslo_messaging:
        username: rabbitmq
    maas:
      admin:
        username: admin
        email: none@none
      postgres:
        username: maas
        database: maasdb
    barbican:
      keystone:
        region_name: RegionOne
        role: admin
        project_name: service
        project_domain_name: default
        user_domain_name: default
        username: barbican
      oslo_db:
        username: barbican
        database: barbican
      oslo_messaging:
        admin:
          username: rabbitmq
        keystone:
          username: keystone
    armada:
      keystone:
        project_domain_name: default
        user_domain_name: default
        project_name: service
        region_name: RegionOne
        role: admin
        user_domain_name: default
        username: armada
    deckhand:
      keystone:
        region_name: RegionOne
        role: admin
        project_name: service
        project_domain_name: default
        user_domain_name: default
        username: deckhand
      postgres:
        username: deckhand
        database: deckhand
  ceph:
    swift:
      keystone:
        role: admin
        region_name: RegionOne
        username: swift
        project_name: service
        user_domain_name: default
        project_domain_name: default
...
