---
schema: armada/ChartGroup/v1
metadata:
  schema: metadata/Document/v1
  name: openstack-compute-kit
  layeringDefinition:
    abstract: false
    layer: global
  storagePolicy: cleartext
data:
  description: Deploy Nova and Neutron
  chart_group:
    - neutron-memcached
    - neutron-rabbitmq
    - neutron
    - nova-memcached
    - nova-rabbitmq
    - nova
