---
schema: armada/ChartGroup/v1
metadata:
  schema: metadata/Document/v1
  name: osh-infra-ingress-controller
  layeringDefinition:
    abstract: false
    layer: global
  storagePolicy: cleartext
data:
  description: OpenStack Namespace Ingress
  chart_group:
    - osh-infra-ingress-controller
