---
schema: armada/ChartGroup/v1
metadata:
  schema: metadata/Document/v1
  name: ucp-divingbell
  layeringDefinition:
    abstract: false
    layer: global
  storagePolicy: cleartext
data:
  description: Divingbell
  chart_group:
    - ucp-divingbell
