---
schema: AccountCatalogue/v1
metadata:
    name: ucp_service_accounts
    layeringDefinition:
        abstract: false
        layer: site
    storagePolicy: cleartext
data:
    ucp:
        postgres:
            admin:
                username: postgres
        oslo_db:
            admin:
                username: root
        oslo_messaging:
            admin:
                username: rabbitmq
        keystone:
            admin:
                region_name: RegionOne
                username: admin
                project_name: admin
                user_domain_name: default
                project_domain_name: default
            oslo_messaging:
                username: rabbitmq
            oslo_db:
                username: keystone
                database: keystone
        promenade:
            keystone:
                region_name: RegionOne
                role: admin
                project_name: service
                project_domain_name: default
                user_domain_name: default
                username: drydock
        drydock:
            keystone:
                region_name: RegionOne
                role: admin
                project_name: service
                project_domain_name: default
                user_domain_name: default
                username: drydock
            postgres:
                username: drydock
                database: drydock
        shipyard:
            keystone:
                region_name: RegionOne
                role: admin
                project_name: service
                project_domain_name: default
                user_domain_name: default
                username: shipyard
            postgres:
                username: shipyard
                database: shipyard
        airflow:
            postgres:
                username: airflow
                database: airflow
            oslo_messaging:
                username: rabbitmq
        maas:
            admin:
                username: admin
                email: none@none
            postgres:
                username: maas
                database: maasdb
        barbican:
            keystone:
                region_name: RegionOne
                role: admin
                project_name: service
                project_domain_name: default
                user_domain_name: default
                username: drydock
            oslo_db:
                username: barbican
                database: barbican
            oslo_messaging:
                username: rabbitmq
        armada:
            keystone:
                project_domain_name: ucp
                project_name: service
                region_name: RegionOne
                role: admin
                user_domain_name: ucp
                username: armada
        deckhand:
            keystone:
                region_name: RegionOne
                role: admin
                project_name: service
                project_domain_name: default
                user_domain_name: default
                username: deckhand
            postgres:
                username: deckhand
                database: deckhand
    ceph:
        swift:
            keystone:
                role: admin
                region_name: RegionOne
                username: swift
                project_name: service
                user_domain_name: default
                project_domain_name: default
...
