---
schema: pegleg/AccountCatalogue/v1
metadata:
  schema: metadata/Document/v1
  name: osh_service_accounts
  layeringDefinition:
    abstract: false
    layer: site
  storagePolicy: cleartext
data:
  osh:
    keystone:
      admin:
        region_name: RegionOne
        username: admin
        project_name: admin
        user_domain_name: default
        project_domain_name: default
      oslo_db:
        username: keystone
        database: keystone
      oslo_messaging:
        admin:
          username: keystone-rabbitmq-admin
        keystone:
          username: keystone-rabbitmq-user
    cinder:
      cinder:
        role: admin
        region_name: RegionOne
        username: cinder
        project_name: service
        user_domain_name: default
        project_domain_name: default
      oslo_db:
        username: cinder
        database: cinder
      oslo_messaging:
        admin:
          username: cinder-rabbitmq-admin
        cinder:
          username: cinder-rabbitmq-user
    glance:
      glance:
        role: admin
        region_name: RegionOne
        username: glance
        project_name: service
        user_domain_name: default
        project_domain_name: default
      oslo_db:
        username: glance
        database: glance
      oslo_messaging:
        admin:
          username: glance-rabbitmq-admin
        glance:
          username: glance-rabbitmq-user
      ceph_object_store:
        username: glance
    heat:
      heat:
        role: admin
        region_name: RegionOne
        username: heat
        project_name: service
        user_domain_name: default
        project_domain_name: default
      heat_trustee:
        role: admin
        region_name: RegionOne
        username: heat-trust
        project_name: service
        user_domain_name: default
        project_domain_name: default
      heat_stack_user:
        role: admin
        region_name: RegionOne
        username: heat-domain
        domain_name: heat
      oslo_db:
        username: heat
        database: heat
      oslo_messaging:
        admin:
          username: heat-rabbitmq-admin
        heat:
          username: heat-rabbitmq-user
    swift:
      swift:
        role: admin
        region_name: RegionOne
        username: swift
        project_name: service
        user_domain_name: default
        project_domain_name: default
    oslo_db:
      admin:
        username: root
    neutron:
      neutron:
        role: admin
        region_name: RegionOne
        username: neutron
        project_name: service
        user_domain_name: default
        project_domain_name: default
      oslo_db:
        username: neutron
        database: neutron
      oslo_messaging:
        admin:
          username: neutron-rabbitmq-admin
        neutron:
          username: neutron-rabbitmq-user
    nova:
      nova:
        role: admin
        region_name: RegionOne
        username: nova
        project_name: service
        user_domain_name: default
        project_domain_name: default
      placement:
        role: admin
        region_name: RegionOne
        username: placement
        project_name: service
        user_domain_name: default
        project_domain_name: default
      oslo_db:
        username: nova
        database: nova
      oslo_db_api:
        username: nova
        database: nova_api
      oslo_db_cell0:
        username: nova
        database: nova_cell0
      oslo_messaging:
        admin:
          username: nova-rabbitmq-admin
        nova:
          username: nova-rabbitmq-user
    horizon:
      oslo_db:
        username: horizon
        database: horizon
    barbican:
      barbican:
        role: admin
        region_name: RegionOne
        username: barbican
        project_name: service
        user_domain_name: default
        project_domain_name: default
      oslo_db:
        username: barbican
        database: barbican
      oslo_messaging:
        admin:
          username: barbican-rabbitmq-admin
        barbican:
          username: barbican-rabbitmq-user
...
---
schema: pegleg/AccountCatalogue/v1
metadata:
  schema: metadata/Document/v1
  name: osh_infra_service_accounts
  layeringDefinition:
      abstract: false
      layer: site
  storagePolicy: cleartext
data:
  osh_infra:
    ldap:
      admin_cn: admin
      admin_domain: cluster.local
      path: /ou=People,dc=cluster,dc=local
    grafana:
      admin:
        username: grafana
      oslo_db:
        username: grafana
        database: grafana
      oslo_db_session:
        username: grafana_session
        database: grafana_session
    elasticsearch:
      admin:
        username: elasticsearch
    oslo_db:
      admin:
        username: root
    prometheus_openstack_exporter:
      user:
        username: prometheus-openstack-exporter
    nagios:
      admin:
        username: nagios
