---
schema: armada/Chart/v1
metadata:
  schema: metadata/Document/v1
  name: osh-horizon
  labels:
    component: horizon
  layeringDefinition:
    abstract: false
    layer: global
  storagePolicy: cleartext
  substitutions:
    # Chart source
    - src:
        schema: pegleg/SoftwareVersions/v1
        name: software-versions
        path: .charts.osh.horizon
      dest:
        path: .source

    # Images
    - src:
        schema: pegleg/SoftwareVersions/v1
        name: software-versions
        path: .images.osh.horizon
      dest:
        path: .values.images.tags

    # Endpoints
    - src:
        schema: pegleg/EndpointCatalogue/v1
        name: osh_endpoints
        path: .osh.identity
      dest:
        path: .values.endpoints.identity
    - src:
        schema: pegleg/EndpointCatalogue/v1
        name: osh_endpoints
        path: .osh.dashboard
      dest:
        path: .values.endpoints.dashboard
    - src:
        schema: pegleg/EndpointCatalogue/v1
        name: osh_endpoints
        path: .osh.oslo_db
      dest:
        path: .values.endpoints.oslo_db
    - src:
        schema: pegleg/EndpointCatalogue/v1
        name: osh_endpoints
        path: .osh.horizon_oslo_cache
      dest:
        path: .values.endpoints.oslo_cache

    # Service Accounts
    - src:
        schema: pegleg/AccountCatalogue/v1
        name: osh_service_accounts
        path: .osh.horizon.oslo_db
      dest:
        path: .values.endpoints.oslo_db.auth.horizon
    - src:
        schema: pegleg/AccountCatalogue/v1
        name: osh_service_accounts
        path: .osh.horizon.oslo_db.database
      dest:
        path: .values.endpoints.oslo_db.path
        pattern: DB_NAME

    # Secrets
    - dest:
        path: .values.endpoints.oslo_db.auth.keystone.password
      src:
        schema: deckhand/Passphrase/v1
        name: osh_horizon_oslo_db_password
        path: .
    - dest:
        path: .values.endpoints.oslo_db.auth.admin.password
      src:
        schema: deckhand/Passphrase/v1
        name: osh_oslo_db_admin_password
        path: .
data:
  chart_name: osh-horizon
  release: osh-horizon
  namespace: openstack
  install:
    no_hooks: false
  upgrade:
    no_hooks: false
  pre:
    delete:
      - name: horizon-db-init
        type: job
        labels:
          - application: horizon
          - component: db-init
          - release_group: osh-horizon
      - name: horizon-db-sync
        type: job
        labels:
          - application: horizon
          - component: db-sync
          - release_group: osh-horizon
  post:
    delete: []
    create: []
  values:
    labels:
      node_selector_key: openstack-control-plane
      node_selector_value: enabled
  dependencies:
    - osh-helm-toolkit
...
