---
schema: armada/Chart/v1
metadata:
  schema: metadata/Document/v1
  name: osh-heat
  labels:
    component: heat
  layeringDefinition:
    abstract: false
    layer: global
  storagePolicy: cleartext
  substitutions:
    # Chart source
    - src:
        schema: pegleg/SoftwareVersions/v1
        name: software-versions
        path: .charts.osh.heat
      dest:
        path: .source

    # Images
    - src:
        schema: pegleg/SoftwareVersions/v1
        name: software-versions
        path: .images.osh.heat
      dest:
        path: .values.images.tags

    # Endpoints
    - src:
        schema: pegleg/EndpointCatalogue/v1
        name: osh_endpoints
        path: .osh.identity
      dest:
        path: .values.endpoints.identity
    - src:
        schema: pegleg/EndpointCatalogue/v1
        name: osh_endpoints
        path: .osh.orchestration
      dest:
        path: .values.endpoints.orchestration
    - src:
        schema: pegleg/EndpointCatalogue/v1
        name: osh_endpoints
        path: .osh.cloudformation
      dest:
        path: .values.endpoints.cloudformation
    - src:
        schema: pegleg/EndpointCatalogue/v1
        name: osh_endpoints
        path: .osh.cloudwatch
      dest:
        path: .values.endpoints.cloudwatch
    - src:
        schema: pegleg/EndpointCatalogue/v1
        name: osh_endpoints
        path: .osh.oslo_db
      dest:
        path: .values.endpoints.oslo_db
    - src:
        schema: pegleg/EndpointCatalogue/v1
        name: osh_endpoints
        path: .osh.heat_oslo_messaging
      dest:
        path: .values.endpoints.oslo_messaging
    - src:
        schema: pegleg/EndpointCatalogue/v1
        name: osh_endpoints
        path: .osh.heat_oslo_cache
      dest:
        path: .values.endpoints.oslo_cache
    - src:
        schema: pegleg/AccountCatalogue/v1
        name: osh_service_accounts
        path: .osh.keystone.admin
      dest:
        path: .values.endpoints.identity.auth.admin
    - src:
        schema: pegleg/AccountCatalogue/v1
        name: osh_service_accounts
        path: .osh.heat.heat
      dest:
        path: .values.endpoints.identity.auth.heat
    - src:
        schema: pegleg/AccountCatalogue/v1
        name: osh_service_accounts
        path: .osh.heat.heat_trustee
      dest:
        path: .values.endpoints.identity.auth.heat_trustee
    - src:
        schema: pegleg/AccountCatalogue/v1
        name: osh_service_accounts
        path: .osh.heat.heat_stack_user
      dest:
        path: .values.endpoints.identity.auth.heat_stack_user
    - src:
        schema: pegleg/AccountCatalogue/v1
        name: osh_service_accounts
        path: .osh.heat.oslo_messaging
      dest:
        path: .values.endpoints.oslo_messaging.auth.heat
    - src:
        schema: pegleg/AccountCatalogue/v1
        name: osh_service_accounts
        path: .osh.heat.oslo_db
      dest:
        path: .values.endpoints.oslo_db.auth.heat
    - src:
        schema: pegleg/AccountCatalogue/v1
        name: osh_service_accounts
        path: .osh.heat.oslo_db.database
      dest:
        path: .values.endpoints.oslo_db.path
        pattern: DB_NAME

    # Secrets
    - dest:
        path: .values.endpoints.identity.auth.admin.password
      src:
        schema: deckhand/Passphrase/v1
        name: osh_keystone_admin_password
        path: .
    - dest:
        path: .values.endpoints.identity.auth.heat.password
      src:
        schema: deckhand/Passphrase/v1
        name: osh_heat_password
        path: .
    - dest:
        path: .values.endpoints.identity.auth.heat_trustee.password
      src:
        schema: deckhand/Passphrase/v1
        name: osh_heat_trustee_password
        path: .
    - dest:
        path: .values.endpoints.identity.auth.heat_stack_user.password
      src:
        schema: deckhand/Passphrase/v1
        name: osh_heat_stack_user_password
        path: .
    - dest:
        path: .values.endpoints.oslo_messaging.auth.heat.password
      src:
        schema: deckhand/Passphrase/v1
        name: osh_heat_oslo_messaging_password
        path: .
    - dest:
        path: .values.endpoints.oslo_db.auth.heat.password
      src:
        schema: deckhand/Passphrase/v1
        name: osh_heat_oslo_db_password
        path: .
    - dest:
        path: .values.endpoints.oslo_db.auth.admin.password
      src:
        schema: deckhand/Passphrase/v1
        name: osh_oslo_db_admin_password
        path: .
data:
  chart_name: osh-heat
  release: osh-heat
  namespace: openstack
  install:
    no_hooks: false
  upgrade:
    no_hooks: false
  pre:
    delete:
      - type: job
        labels:
          application: heat
          component: db-init
      - type: job
        labels:
          application: heat
          component: db-sync
      - type: job
        labels:
          application: heat
          component: ks-user
      - type: job
        labels:
          application: heat
          component: ks-service
      - type: job
        labels:
          application: heat
          component: ks-endpoints
  post:
    delete: []
    create: []
  values:
    pods:
      replicas:
        api: 2
        cfn: 2
        cloudwatch: 2
        engine: 2
    labels:
      api:
        node_selector_key: openstack-control-plane
        node_selector_value: enabled
      cfn:
        node_selector_key: openstack-control-plane
        node_selector_value: enabled
      cloudwatch:
        node_selector_key: openstack-control-plane
        node_selector_value: enabled
      engine:
        node_selector_key: openstack-control-plane
        node_selector_value: enabled
      job:
        node_selector_key: openstack-control-plane
        node_selector_value: enabled
  dependencies:
    - osh-helm-toolkit
...
