---
schema: armada/ChartGroup/v1
metadata:
  schema: metadata/Document/v1
  name: openstack-barbican
  layeringDefinition:
    abstract: false
    layer: global
  storagePolicy: cleartext
data:
  description: Deploy Glance
  chart_group:
    - barbican-memcached
    - barbican-rabbitmq
    - barbican
