---
schema: armada/Chart/v1
metadata:
  schema: metadata/Document/v1
  name: haproxy
  layeringDefinition:
    abstract: false
    layer: global
  storagePolicy: cleartext
  substitutions:

    # Chart source
    - src:
        schema: pegleg/SoftwareVersions/v1
        name: software-versions
        path: .charts.kubernetes.haproxy
      dest:
        path: .source

    # Images
    - src:
        schema: pegleg/SoftwareVersions/v1
        name: software-versions
        path: .images.kubernetes.haproxy
      dest:
        path: .values.images
data:
  chart_name: haproxy
  release: haproxy
  namespace: kube-system
  timeout: 600
  wait:
    timeout: 600
  upgrade:
    no_hooks: true
  values:
    conf:
      anchor:

        # TODO(alanmeadows) this should be substituted
        kubernetes_url: https://10.96.0.1:443
        services:
          default:
            kubernetes:
              server_opts: "check"
              conf_parts:
                frontend:
                  - mode tcp
                  - option tcpka
                  - bind *:6553
                backend:
                  - mode tcp
                  - option tcpka
          kube-system:
            kubernetes-etcd:
              server_opts: "check"
              conf_parts:
                frontend:
                  - mode tcp
                  - option tcpka
                  - bind *:2378
                backend:
                  - mode tcp
                  - option tcpka
  dependencies:
    - haproxy-htk
---
schema: armada/Chart/v1
metadata:
  schema: metadata/Document/v1
  name: haproxy-htk
  layeringDefinition:
    abstract: false
    layer: global
  storagePolicy: cleartext
  substitutions:
    - src:
        schema: pegleg/SoftwareVersions/v1
        name: software-versions
        path: .charts.kubernetes.haproxy-htk
      dest:
        path: .source
data:
  chart_name: haproxy-htk
  release: haproxy-htk
  namespace: haproxy-htk
  timeout: 100
  values: {}
  dependencies: []
...
