---
schema: armada/ChartGroup/v1
metadata:
  schema: metadata/Document/v1
  name: ucp-drydock
  layeringDefinition:
    abstract: false
    layer: global
  storagePolicy: cleartext
data:
  description: Drydock
  chart_group:
    - ucp-maas
    - ucp-drydock
