---
schema: armada/Chart/v1
metadata:
  schema: metadata/Document/v1
  name: ucp-tiller
  layeringDefinition:
    abstract: false
    layer: global
  storagePolicy: cleartext
  substitutions:
    # Chart source
    - src:
        schema: SoftwareVersions/v1
        name: software-versions
        path: .charts.ucp.tiller
      dest:
        path: .source

    # Images
    - src:
        schema: SoftwareVersions/v1
        name: software-versions
        path: .images.ucp.tiller
      dest:
        path: .values.images.tags

data:
  chart_name: tiller
  release: ucp-tiller
  namespace: kube-system
  install:
    no_hooks: false
  upgrade:
    no_hooks: false
  values: {}
  dependencies:
    - tiller_htk
...
---
schema: armada/Chart/v1
metadata:
  schema: metadata/Document/v1
  name: tiller_htk
  layeringDefinition:
    abstract: false
    layer: global
  storagePolicy: cleartext
data:
  chart_name: tiller_htk
  release: tiller_htk
  namespace: tiller_htk
  timeout: 100
  values: {}
  source:
    type: git
    location: https://github.com/openstack/openstack-helm
    subpath: helm_toolkit
    reference: e4dd1ba91a9e3c517b0f4594c70eb9a743681432
  dependencies: []
...
