---
schema: armada/Chart/v1
metadata:
  schema: metadata/Document/v1
  name: neutron
  labels:
    component: neutron
  layeringDefinition:
    abstract: false
    layer: global
  storagePolicy: cleartext
  substitutions:
    # Chart source
    - src:
        schema: pegleg/SoftwareVersions/v1
        name: software-versions
        path: .charts.osh.neutron
      dest:
        path: .source

    # Images
    - src:
        schema: pegleg/SoftwareVersions/v1
        name: software-versions
        path: .images.osh.neutron
      dest:
        path: .values.images.tags

    # Endpoints
    - src:
        schema: pegleg/EndpointCatalogue/v1
        name: osh_endpoints
        path: .osh.identity
      dest:
        path: .values.endpoints.identity
    - src:
        schema: pegleg/EndpointCatalogue/v1
        name: osh_endpoints
        path: .osh.compute
      dest:
        path: .values.endpoints.compute
    - src:
        schema: pegleg/EndpointCatalogue/v1
        name: osh_endpoints
        path: .osh.compute_metadata
      dest:
        path: .values.endpoints.image_registry
    - src:
        schema: pegleg/EndpointCatalogue/v1
        name: osh_endpoints
        path: .osh.oslo_db
      dest:
        path: .values.endpoints.oslo_db
    - src:
        schema: pegleg/EndpointCatalogue/v1
        name: osh_endpoints
        path: .osh.neutron_oslo_messaging
      dest:
        path: .values.endpoints.oslo_messaging
    - src:
        schema: pegleg/EndpointCatalogue/v1
        name: osh_endpoints
        path: .osh.neutron_oslo_cache
      dest:
        path: .values.endpoints.oslo_cache
    - src:
        schema: pegleg/EndpointCatalogue/v1
        name: osh_endpoints
        path: .osh.network
      dest:
        path: .values.endpoints.network
    - src:
        schema: pegleg/AccountCatalogue/v1
        name: osh_service_accounts
        path: .osh.keystone.admin
      dest:
        path: .values.endpoints.identity.auth.admin
    - src:
        schema: pegleg/AccountCatalogue/v1
        name: osh_service_accounts
        path: .osh.neutron.neutron
      dest:
        path: .values.endpoints.identity.auth.neutron
    - src:
        schema: pegleg/AccountCatalogue/v1
        name: osh_service_accounts
        path: .osh.nova.nova
      dest:
        path: .values.endpoints.identity.auth.nova
    - src:
        schema: pegleg/AccountCatalogue/v1
        name: osh_service_accounts
        path: .osh.neutron.oslo_messaging
      dest:
        path: .values.endpoints.oslo_messaging.auth.neutron
    - src:
        schema: pegleg/AccountCatalogue/v1
        name: osh_service_accounts
        path: .osh.neutron.oslo_db
      dest:
        path: .values.endpoints.oslo_db.auth.neutron
    - src:
        schema: pegleg/AccountCatalogue/v1
        name: osh_service_accounts
        path: .osh.neutron.oslo_db.database
      dest:
        path: .values.endpoints.oslo_db.path
        pattern: DB_NAME

    # Secrets
    - dest:
        path: .values.endpoints.identity.auth.admin.password
      src:
        schema: deckhand/Passphrase/v1
        name: osh_keystone_admin_password
        path: .
    - dest:
        path: .values.endpoints.identity.auth.glance.password
      src:
        schema: deckhand/Passphrase/v1
        name: osh_neutron_password
        path: .
    - dest:
        path: .values.endpoints.oslo_messaging.auth.glance.password
      src:
        schema: deckhand/Passphrase/v1
        name: osh_neutron_oslo_messaging_password
        path: .
    - dest:
        path: .values.endpoints.oslo_db.auth.glance.password
      src:
        schema: deckhand/Passphrase/v1
        name: osh_neutron_oslo_db_password
        path: .
    - dest:
        path: .values.endpoints.oslo_db.auth.admin.password
      src:
        schema: deckhand/Passphrase/v1
        name: osh_oslo_db_admin_password
        path: .

    # Interfaces for neutron configuration
    - src:
        schema: pegleg/CommonAddresses/v1
        name: common-addresses
        path: .neutron.tunnel_device
      dest:
        path: .values.network.interface.tunnel
        pattern: 'TUNNEL_DEVICE'
    - src:
        schema: pegleg/CommonAddresses/v1
        name: common-addresses
        path: .neutron.external_iface
      dest:
        path: .values.network.interface.external
        pattern: 'EXTERNAL_INTERFACE'

data:
  chart_name: neutron
  release: neutron
  namespace: openstack
  install:
    no_hooks: false
  upgrade:
    no_hooks: false
    pre:
      delete:
        - type: job
          labels:
            application: neutron
            component: db-init
        - type: job
          labels:
            application: neutron
            component: db-sync
        - type: job
          labels:
            application: neutron
            component: ks-user
        - type: job
          labels:
            application: neutron
            component: ks-service
        - type: job
          labels:
            application: neutron
            component: ks-endpoints
  post:
    delete: []
    create: []
  values:
    pods:
      replicas:
        server: 2
    labels:
      agent:
        dhcp:
          node_selector_key: openstack-control-plane
          node_selector_value: enabled
        l3:
          node_selector_key: openstack-control-plane
          node_selector_value: enabled
        metadata:
          node_selector_key: openstack-control-plane
          node_selector_value: enabled
      job:
        node_selector_key: openstack-control-plane
        node_selector_value: enabled
      lb:
        node_selector_key: linuxbridge
        node_selector_value: enabled
      ovs:
        node_selector_key: openvswitch
        node_selector_value: enabled
      server:
        node_selector_key: openstack-control-plane
        node_selector_value: enabled
      test:
        node_selector_key: openstack-control-plane
        node_selector_value: enabled
    network:
      interface:
        tunnel: 'TUNNEL_DEVICE'
        external: 'EXTERNAL_INTERFACE'
    conf:
      neutron:
        DEFAULT:
          l3_ha: True
          min_l3_agents_per_router: 2
          max_l3_agents_per_router: 5
          l3_ha_network_type: vxlan
          dhcp_agents_per_network: 2
      plugins:
        ml2_conf:
          ml2_type_flat:
            flat_networks: public
        openvswitch_agent:
          agent:
            tunnel_types: vxlan
          ovs:
            bridge_mappings: public:br-ex
  dependencies:
    - osh-helm-toolkit
...
