---
schema: armada/ChartGroup/v1
metadata:
  schema: metadata/Document/v1
  name: ucp-promenade
  layeringDefinition:
    abstract: false
    layer: global
  storagePolicy: cleartext
data:
  description: Promenade
  chart_group:
    - ucp-promenade
