---
schema: armada/Chart/v1
metadata:
  schema: metadata/Document/v1
  name: ucp-promenade
  layeringDefinition:
    abstract: false
    layer: global
  storagePolicy: cleartext
  substitutions:
    # Chart source
    - src:
        schema: pegleg/SoftwareVersions/v1
        name: software-versions
        path: .charts.ucp.promenade
      dest:
        path: .source

    # Images
    - src:
        schema: pegleg/SoftwareVersions/v1
        name: software-versions
        path: .images.ucp.promenade
      dest:
        path: .values.images.tags

    # Endpoints

    - src:
        schema: EndpointCatalogue/v1
        name: ucp_endpoints
        path: .ucp.identity
      dest:
        path: .values.endpoints.identity
    - src:
        schema: EndpointCatalogue/v1
        name: ucp_endpoints
        path: .ucp.kubernetesprovisioner
      dest:
        path: .values.endpoints.kubernetesprovisioner

    # Credentials

    - src:
        schema: AccountCatalogue/v1
        name: ucp_service_accounts
        path: .ucp.keystone.admin
      dest:
        path: .values.endpoints.identity.auth.admin
    - src:
        schema: AccountCatalogue/v1
        name: ucp_service_accounts
        path: .ucp.promenade.keystone
      dest:
        path: .values.endpoints.identity.auth.user

    # Secrets
    - dest:
        path: .values.endpoints.identity.auth.admin.password
      src:
        schema: deckhand/Passphrase/v1
        name: ucp_keystone_admin_password
        path: .
    - dest:
        path: .values.endpoints.identity.auth.user.password
      src:
        schema: deckhand/Passphrase/v1
        name: ucp_promenade_keystone_password
        path: .

data:
  chart_name: promenade
  release: ucp-promenade
  namespace: ucp
  install:
    no_hooks: false
  upgrade:
    no_hooks: false
  values:
    pod:
      env:
        promenade_api:
          - name: http_proxy
            value: http://one.proxy.att.com:8080
          - name: HTTP_PROXY
            value: http://one.proxy.att.com:8080
          - name: https_proxy
            value: http://one.proxy.att.com:8080
          - name: HTTPS_PROXY
            value: http://one.proxy.att.com:8080
          - name: no_proxy
            value: 10.96.0.1,*.cluster.local
          - name: NO_PROXY
            value: 10.96.0.1,*.cluster.local
    conf:
      promenade:
        keystone_authtoken:
          username: promenade
          domain_name: default
          auth_url: http://keystone-api.ucp.svc.cluster.local/
      paste:
        filter:authtoken:
          paste.filter_factory: keystonemiddleware.auth_token:filter_factory
          admin_tenant_name: service
          admin_user: promenade
          delay_auth_decision: true
          identity_uri: http://keystone-api.ucp.svc.cluster.local/
          service_token_roles_required: true
  dependencies:
    - promenade_htk
...
---
schema: armada/Chart/v1
metadata:
  schema: metadata/Document/v1
  name: promenade_htk
  layeringDefinition:
    abstract: false
    layer: global
  storagePolicy: cleartext
data:
  chart_name: promenade_htk
  release: promenade_htk
  namespace: promenade_htk
  timeout: 100
  values: {}
  source:
    type: git
    location: https://github.com/openstack/openstack-helm
    subpath: helm_toolkit
    reference: e4dd1ba91a9e3c517b0f4594c70eb9a743681432
  dependencies: []
...
