---
schema: armada/Chart/v1
metadata:
  schema: metadata/Document/v1
  name: kubernetes-calico
  layeringDefinition:
    abstract: false
    layer: site
    parentSelector:
        name: kubernetes-calico-global
    actions:
        - method: merge
          path: .
  storagePolicy: cleartext
  substitutions:
    # IP addresses
    - src:
        schema: pegleg/CommonAddresses/v1
        name: common-addresses
        path: .calico.etcd.service_ip
      dest:
        path: .values.endpoints.etcd.host_fqdn_override.default
    - src:
        schema: pegleg/CommonAddresses/v1
        name: common-addresses
        path: .kubernetes.pod_cidr
      dest:
        path: .values.networking.podSubnet
    - src:
        schema: pegleg/CommonAddresses/v1
        name: common-addresses
        path: .kubernetes.api_service_ip
      dest:
        path: .values.conf.policy_controller.K8S_API
        pattern: SUB_KUBERNETES_IP
    # Other site-specific configuration
    - src:
        schema: pegleg/CommonAddresses/v1
        name: common-addresses
        path: .calico.ip_autodetection_method
      dest:
        path: .values.conf.node.IP_AUTODETECTION_METHOD

    # Certificates
    - src:
        schema: deckhand/CertificateAuthority/v1
        name: calico-etcd
        path: .
      dest:
        path: .values.endpoints.etcd.auth.client.tls.ca
    - src:
        schema: deckhand/Certificate/v1
        name: calico-node
        path: .
      dest:
        path: .values.endpoints.etcd.auth.client.tls.crt
    - src:
        schema: deckhand/CertificateKey/v1
        name: calico-node
        path: .
      dest:
        path: .values.endpoints.etcd.auth.client.tls.key
data:
  chart_name: calico
  release: calico
  namespace: kube-system
  timeout: 600
  upgrade:
    no_hooks: true
  values:
    conf:
      cni_network_config:
        name: k8s-pod-network
        cniVersion: 0.1.0
        type: calico
        etcd_endpoints: __ETCD_ENDPOINTS__
        etcd_ca_cert_file: /etc/calico/pki/ca
        etcd_cert_file: /etc/calico/pki/crt
        etcd_key_file: /etc/calico/pki/key
        log_level: info
        mtu: 1500
        ipam:
          type: calico-ipam
        policy:
          type: k8s
          k8s_api_root: https://__KUBERNETES_SERVICE_HOST__:__KUBERNETES_SERVICE_PORT__
          k8s_auth_token: __SERVICEACCOUNT_TOKEN__

      policy_controller:
        K8S_API: "https://SUB_KUBERNETES_IP:443"

      node:
        CALICO_STARTUP_LOGLEVEL: INFO
        CLUSTER_TYPE:
          - k8s
          - bgp
        WAIT_FOR_STORAGE: "true"

    endpoints:
      etcd:
        hosts:
          default: calico-etcd
        scheme:
          default: https

    networking:
      mtu: 1500

    manifests:
      daemonset_calico_etcd: false
      job_image_repo_sync: false
      service_calico_etcd: false
  dependencies:
    - calico-htk
---
schema: armada/Chart/v1
metadata:
  schema: metadata/Document/v1
  name: calico-htk
  layeringDefinition:
    abstract: false
    layer: global
  storagePolicy: cleartext
  substitutions:
    - src:
        schema: pegleg/SoftwareVersions/v1
        name: software-versions
        path: .charts.kubernetes.calico.calico-htk
      dest:
        path: .source
data:
  chart_name: calico-htk
  release: calico-htk
  namespace: calico-htk
  timeout: 600
  values: {}
  dependencies: []
...
