---
schema: promenade/Genesis/v1
metadata:
  schema: metadata/Document/v1
  name: genesis
  layeringDefinition:
    abstract: false
    layer: site
data:
  hostname: genesis
  ip: 10.24.20.100
  labels:
    static:
      - node-role.kubernetes.io/master=
    dynamic:
      - calico-etcd=enabled
      - kubernetes-apiserver=enabled
      - kubernetes-controller-manager=enabled
      - kubernetes-etcd=enabled
      - kubernetes-scheduler=enabled
      - promenade-genesis=enabled
      - ucp-control-plane=enabled
      - ceph-mon=enabled
      - ceph-osd=enabled
      - ceph-mds=enabled
      - ceph-rgw=enabled
  images:
    armada: quay.io/attcomdev/armada:master
    helm:
      tiller: gcr.io/kubernetes-helm/tiller:v2.7.0
    kubernetes:
      apiserver: gcr.io/google_containers/hyperkube-amd64:v1.8.0
      controller-manager: gcr.io/google_containers/hyperkube-amd64:v1.8.0
      etcd: quay.io/coreos/etcd:v3.0.17
      scheduler: gcr.io/google_containers/hyperkube-amd64:v1.8.0
  files:
    - path: /var/lib/anchor/calico-etcd-bootstrap
      content: ""
      mode: 0644
...
