---
schema: armada/ChartGroup/v1
metadata:
  schema: metadata/Document/v1
  name: osh-infra-logging
  layeringDefinition:
    abstract: false
    layer: global
  storagePolicy: cleartext
data:
  description: OSH Infra Monitoring
  chart_group:
    - osh-infra-prometheus
    - osh-infra-prometheus-alertmanager
    - osh-infra-prometheus-node-exporter
    - osh-infra-prometheus-kube-state-metrics
    - osh-infra-grafana
