---
schema: armada/Chart/v1
metadata:
  schema: metadata/Document/v1
  name: nagios
  layeringDefinition:
    abstract: false
    layer: global
  storagePolicy: cleartext
  substitutions:
    # Chart source
    - src:
        schema: pegleg/SoftwareVersions/v1
        name: software-versions
        path: .charts.osh_infra.nagios
      dest:
        path: .source

    # Images
    - src:
        schema: pegleg/SoftwareVersions/v1
        name: software-versions
        path: .images.osh_infra.nagios
      dest:
        path: .values.images.tags

    # Endpoints
    - src:
        schema: pegleg/EndpointCatalogue/v1
        name: osh_infra_endpoints
        path: .osh_infra.nagios
      dest:
        path: .values.endpoints.nagios
    - src:
        schema: pegleg/EndpointCatalogue/v1
        name: osh_infra_endpoints
        path: .osh_infra.monitoring
      dest:
        path: .values.endpoints.monitoring

    # Accounts
    - src:
        schema: pegleg/AccountCatalogue/v1
        name: osh_infra_service_accounts
        path: .osh_infra.nagios.admin
      dest:
        path: .values.endpoints.nagios.auth.admin

    # Secrets
    - dest:
        path: .values.endpoints.nagios.auth.admin.password
      src:
        schema: deckhand/Passphrase/v1
        name: osh_infra_nagios_admin_password
        path: .

data:
  chart_name: nagios
  release: nagios
  namespace: osh-infra
  install:
    no_hooks: false
  upgrade:
    no_hooks: false
    pre:
      delete: []
      create: []
    post:
      create: []
  values:
    labels:
      nagios:
        node_selector_key: openstack-control-plane
        node_selector_value: enabled
      job:
        node_selector_key: openstack-control-plane
        node_selector_value: enabled
    pod:
      replicas:
        nagios: 3
  dependencies:
    - osh-infra-helm-toolkit
...
