---
schema: armada/ChartGroup/v1
metadata:
  schema: metadata/Document/v1
  name: osh-ceph-config
  layeringDefinition:
    abstract: false
    layer: global
  storagePolicy: cleartext
data:
  description: Ceph config for OpenStack namespace(s)
  chart_group:
    - osh-ceph-config
