---
schema: armada/Chart/v1
metadata:
  schema: metadata/Document/v1
  name: ingress-kube-system
  layeringDefinition:
    abstract: false
    layer: global
  storagePolicy: cleartext
  substitutions:
    # Chart source
    - src:
        schema: pegleg/SoftwareVersions/v1
        name: software-versions
        path: .charts.kubernetes.ingress
      dest:
        path: .source
data:
  chart_name: ingress-kube-system
  release: ingress-kube-system
  namespace: kube-system
  timeout: 300
  install:
    no_hooks: false
  upgrade:
    no_hooks: false
  values:
    labels:
      server:
        node_selector_key: kube-ingress
        node_selector_value: enabled
      error_server:
        node_selector_key: kube-ingress
        node_selector_value: enabled
    deployment:
      mode: cluster
      type: DaemonSet
    network:
      host_namespace: true
      ingress:
        annotations:
          nginx.ingress.kubernetes.io/proxy-read-timeout: "603"
    pod:
      replicas:
        error_page: 2
