---
schema: armada/Chart/v1
metadata:
  schema: metadata/Document/v1
  name: ucp-barbican
  layeringDefinition:
    abstract: false
    layer: global
  storagePolicy: cleartext
  substitutions:
    # Chart source
    - src:
        schema: SoftwareVersions/v1
        name: software-versions
        path: .charts.ucp.barbican
      dest:
        path: .source

    # Images
    - src:
        schema: SoftwareVersions/v1
        name: software-versions
        path: .images.ucp.barbican
      dest:
        path: .values.images.tags

    # Endpoints
    - src:
        schema: EndpointCatalogue/v1
        name: ucp_endpoints
        path: .ucp.identity
      dest:
        path: .values.endpoints.identity
    - src:
        schema: EndpointCatalogue/v1
        name: ucp_endpoints
        path: .ucp.key_manager
      dest:
        path: .values.endpoints.key_manager
    - src:
        schema: EndpointCatalogue/v1
        name: ucp_endpoints
        path: .ucp.oslo_cache
      dest:
        path: .values.endpoints.oslo_cache
    - src:
        schema: EndpointCatalogue/v1
        name: ucp_endpoints
        path: .ucp.oslo_messaging
      dest:
        path: .values.endpoints.oslo_messaging

    # Credentials
    - src:
        schema: AccountCatalogue/v1
        name: ucp_service_accounts
        path: .ucp.barbican.keystone
      dest:
        path: .values.endpoints.identity.auth.barbican
    - src:
        schema: AccountCatalogue/v1
        name: ucp_service_accounts
        path: .ucp.keystone.admin
      dest:
        path: .values.endpoints.identity.auth.admin
    - src:
        schema: AccountCatalogue/v1
        name: ucp_service_accounts
        path: .ucp.barbican.oslo_db
      dest:
        path: .values.endpoints.oslo_db.auth.barbican
    - src:
        schema: AccountCatalogue/v1
        name: ucp_service_accounts
        path: .ucp.barbican.oslo_db.database
      dest:
        path: .values.endpoints.oslo_db.path
        pattern: DB_NAME
    - src:
        schema: AccountCatalogue/v1
        name: ucp_service_accounts
        path: .ucp.barbican.oslo_messaging
      dest:
        path: .values.endpoints.oslo_messaging.auth.barbican

    # Secrets
    - dest:
        path: .values.endpoints.identity.auth.admin.password
      src:
        schema: deckhand/Passphrase/v1
        name: ucp_keystone_admin_password
        path: .
    - dest:
        path: .values.endpoints.oslo_db.auth.admin.password
      src:
        schema: deckhand/Passphrase/v1
        name: ucp_oslo_db_admin_password
        path: .
    - dest:
        path: .values.endpoints.identity.auth.barbican.password
      src:
        schema: deckhand/Passphrase/v1
        name: ucp_barbican_keystone_password
        path: .
    - dest:
        path: .values.endpoints.oslo_db.auth.barbican.password
      src:
        schema: deckhand/Passphrase/v1
        name: ucp_barbican_oslo_db_password
        path: .
    - dest:
        path: .values.endpoints.oslo_messaging.auth.barbican.password
      src:
        schema: deckhand/Passphrase/v1
        name: ucp_oslo_messaging_password
        path: .
data:
  chart_name: ucp-barbican
  release: ucp-barbican
  namespace: ucp
  install:
    no_hooks: false
  upgrade:
    no_hooks: false
  pre:
    delete: []
    create: []
  post:
    delete: []
    create: []
  values:
    pod:
      replicas:
        api: 2
  dependencies:
    - ucp_barbican_htk
...
---
schema: armada/Chart/v1
metadata:
  schema: metadata/Document/v1
  name: _ucp_barbican_htk
  layeringDefinition:
    abstract: false
    layer: global
  storagePolicy: cleartext
data:
  chart_name: ucp_barbican_htk
  release: ucp_barbican_htk
  namespace: ucp_barbican_htk
  timeout: 100
  values: {}
  source:
    type: git
    location: https://github.com/openstack/openstack-helm
    subpath: helm_toolkit
    reference: e4dd1ba91a9e3c517b0f4594c70eb9a743681432
  dependencies: []
...
