---
schema: armada/Chart/v1
metadata:
  schema: metadata/Document/v1
  name: osh-ingress
  layeringDefinition:
    abstract: false
    layer: global
  storagePolicy: cleartext
  substitutions:
    # Chart source
    - src:
        schema: pegleg/SoftwareVersions/v1
        name: software-versions
        path: .charts.osh.ingress
      dest:
        path: .source
data:
  chart_name: ingress
  release: ingress
  namespace: openstack
  timeout: 300
  install:
    no_hooks: false
  upgrade:
    no_hooks: false
  values:
    labels:
      server:
        node_selector_key: openstack-control-plane
        node_selector_value: enabled
      error_server:
        node_selector_key: openstack-control-plane
        node_selector_value: enabled
    pod:
      replicas:
        ingress: 2
        error_page: 2
  dependencies:
    - osh-helm-toolkit
