---
# TODO: Move this to all charts to pin HTK version to chart. Leaving here for
#       time being until all references are migrated.
schema: armada/Chart/v1
metadata:
  schema: metadata/Document/v1
  name: ucp-helm-toolkit
  layeringDefinition:
    abstract: false
    layer: global
  storagePolicy: cleartext
  substitutions:
    - src:
        schema: pegleg/SoftwareVersions/v1
        name: software-versions
        path: .charts.dependencies.ucp-helm-toolkit
      dest:
        path: .source
data:
  chart_name: helm-toolkit
  release: ucp-helm-toolkit
  namespace: ucp-helm-toolkit
  timeout: 600
  wait:
    timeout: 600
  upgrade:
    no_hooks: true
  values: {}
  dependencies: []
